### ISSUE TITLE
How to turn off all linguistics processing for index and query?

### ISSUE THREAD

**Issue by luoyetx** [vespa-engine/vespa#10655]
Any configuration to turn off the processing rather than rewriting the Linguistics?

**Comment by bratseth** [comment]
What processing precisely? 

If you want to turn off tokenization you can use match:exact, or match:word, then each field will be indexed as a single string containing the characters you write, after lowercasing.

If you want to turn off stemming, use stemming:none on the field or entire search definition.

If you want to turn off accent normalizing, then set normalizing:false on the field or entire search definition.

Refer to https://docs.vespa.ai/documentation/reference/search-definitions-reference.html

**Comment by luoyetx** [comment]
```java
private String processToken(String token, Language language, StemMode stemMode, boolean removeAccents) {
        token = normalizer.normalize(token);
        token = LinguisticsCase.toLowerCase(token);
        if (removeAccents)
            token = transformer.accentDrop(token, language);
        if (stemMode != StemMode.NONE)
            token = stemmer.stem(token);
```

I want to configure `removeAccents=False` and `stemMode=StemMode.NONE` on entire search. And how about the query?

**Comment by bratseth** [comment]
The query always follows what you configure for the field in the search definition.

Stemming: Set stemming:none on the entire search definition: https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#stemming

Accent normalizing: Set normalizing:none on each field (it turns out this cannot be done over all fields as I wrote above): https://docs.vespa.ai/documentation/reference/search-definitions-reference.html#normalizing

**Comment by luoyetx** [comment]
Thanks!
