### ISSUE TITLE
Add new content in services.xml causes distributor2 start failed on some nodes

### ISSUE THREAD

**Issue by luoyetx** [vespa-engine/vespa#11196]
Add a new content in services.xml and deploy the application. port of  distributor conflicts with port of container on some nodes. Restart these two services with vespa-sentinel-cmd solve the problem. 

When deploy the application. The debug info gives restart topleveldispatch service.

**Comment by luoyetx** [comment]
got some error when send search request
```
status error: status: 503 error: {"root":{"id":"toplevel","relevance":1.0,"fields":{"totalCount":0},"errors":[{"code":0,"summary":"No backends in service. Try later","source":"mt_video","message":"Could not search"}]}}
```

**Comment by luoyetx** [comment]
restart all with `vespa-sentinel-cmd restart container` on all node solve this problem in a few minutes when restart done.

**Comment by hmusum** [comment]
Adding or removing services on a node will lead to changes that requires restart of some services (since we allocate ports dynamically). When response from deployment says to restart services that has to be done, otherwise the system will not work. 

To avoid having to deal with restarts after changes like this you could make sure to run only one cluster instance on each node. Alternatively, you could look at our hosted solution (https://cloud.vespa.ai/, invite-only at the moment) which will solve issues like this and take care of operations in general for you.
