### ISSUE TITLE
Partial update on position field fails despite HTTP 200

### ISSUE THREAD

**Issue by wardsng** [vespa-engine/vespa#11208]
Hello! I have a position field called `latLong` and when trying to do a partial update (via HTTP PUT at via HTTP PUT `/document/v1/cluster/sd/docid/1` like so
```
{   
 "fields": {
        "latLong": {
            "assign": "N37.401;W121.996"
        }
    },
    "create": true
}
```
I get back an HTTP 200. However, issuing a subsequent HTTP GET at the path `/document/v1/cluster/sd/docid/1` does not show a `latLong` field at all. If I do a PUT (via HTTP POST `/document/v1/cluster/sd/docid/1`) like so:
```
{
    "fields": {
        "latLong": "N37.401;W121.996"
    }
}
```
doing a subsequent HTTP GET then shows that the `latLong` field is correctly inserted. 
```
"latLong": { "x": -121996000, "y": 37401000 },
```

It looks like an incremental update of `latLong` will now work, but not when `latLong` never previoiusly existed previously on the document. This seems like a bug since I get the expected behavior for other field types (i.e. that an incremental update creates it if it doesn't exist)?

**Comment by vekterli** [comment]
I'm attempting to reproduce this locally, but from what I can see things work as expected. Can you verify if what I'm trying to do matches your observations?

Search definition excerpt:
```
    field my_location type position {
        indexing: attribute
    }
```

Commands run:
```sh
$ cat myupdate.json 
{
  "create": true,
  "fields":{
    "my_location":{
      "assign":"N37.401;W121.996"
    }
  }
}

$ curl -s -H "Content-Type: application/json" -T myupdate.json 'http://localhost:19020/document/v1/storage_test/music/number/2/8'
{"id":"id:storage_test:music:n=2:8","pathId":"/document/v1/storage_test/music/number/2/8"}

$ curl -s 'http://localhost:19020/document/v1/storage_test/music/number/2/8' | python -m json.tool
{
    "fields": {
        "my_location": {
            "x": -121996000,
            "y": 37401000
        }
    },
    "id": "id:storage_test:music:n=2:8",
    "pathId": "/document/v1/storage_test/music/number/2/8"
}
```

**Comment by wardsng** [comment]
Those look to be the same steps. This is on Vespa version 7.132.16 (also tried on 7.128.18). Tried recreating with your steps.

search definition excerpt:
```
field latLong type position {
    indexing: attribute
}
```
commands run:
```
$ cat myupdate.json
{
    "create": true,
    "fields": {
        "latLong": {
            "assign": "N37.401;W121.996"
        }
    }
}

$ curl -s 'http://localhost:5555/document/v1/user/userFull/docid/5' | python -m json.tool
{
    "id": "id:user:userFull::5",
    "pathId": "/document/v1/user/userFull/docid/5"
}

$ curl -s -H "Content-Type: application/json" -T myupdate.json 'http://localhost:5555/document/v1/user/userFull/docid/5'
{"id":"id:user:userFull::5","pathId":"/document/v1/user/userFull/docid/5"

$ curl -s 'http://localhost:5555/document/v1/user/userFull/docid/5' | python -m json.tool
{
    "fields": {
        "isIncognito": false,
        "pictureActive": false
    },
    "id": "id:user:userFull::5",
    "pathId": "/document/v1/user/userFull/docid/5"
}
```
The only fields that appeared in the final GET were booleans (I've removed a few from the response above), with no latLong present

The two fields highlighted above are:
```
        field isIncognito type bool {
            indexing: summary | attribute
        }
        field pictureActive type bool {
            indexing: attribute
        }
```
(the rest that were removed from the response would be similar too)

**Comment by vekterli** [comment]
Update: when I tried to reproduce this earlier it was on top of an existing test application which had `mode="store-only"` for the document type. Using `mode="index"` I get the same results as you do (i.e. the update is silently discarded).

That narrows the problem location down to somewhere in the indexing document processing pipeline, and happens before reaching the content node backends.

**Comment by vekterli** [comment]
Turns out this issue also applies to partial updates for existing documents when the previous document version did not originally have the position field set by a Put operation.

A position field in an indexed setup is backed by an internal "shadow" Z-curve attribute that acts as the source of truth of the field's contents. When doing a document Put, the backend receives a document containing the position struct _and_ the zcurve shadow field (added in the indexing document processing pipeline). When doing a partial update, an update is _only_ received for the zcurve field. This includes updates that clear the position field.

There is an inconsistency in how the search core handles position fields when retrieving them (for Gets etc), since it currently checks if the _position struct field_ from the document store is present when deciding whether to include the field or not. If the position struct field is present, the zcurve is decoded and whatever it contains will be returned as the X/Y values regardless of what's in the docstore. The latter is fine since the zcurve attribute is authoritative, but the former causes several issues:

1) If a position field is created via a partial update to the zcurve attribute there will be no position struct field present. The document should still give correct results for position searches, as these use the zcurve directly, but from the perspective of Get operations it's as if the field is not set
2) If a position field is cleared, the struct field does not receive a `ClearValueUpdate`, only the zurve. Since the position field is still present in the docstore, the position field will be rendered with bogus X/Y coordinates decoded from the "no value set" sentinel zcurve attribute value.

Consulting the zcurve attribute instead of the docstore when deciding field presence resolves both these.
