### ISSUE TITLE
Querying Vespa using flexible full text search

### ISSUE THREAD

**Issue by maudetes** [vespa-engine/vespa#12154]
Hello,

We are using vespa for full text search and we have some questions on the first search phase.

To explain our issue, we use the sample app provided at https://github.com/vespa-engine/sample-apps/tree/master/album-recommendation-selfhosted/.
Let's say we want to make a full text search on album + artist. In the search definition, we keep indexation as is (default match is `text`) and we create a default fieldset containing both fields.
```
fieldset default {
    fields: artist, album
}
```

In order to search for "Hardwired...To Self-Destruct" by "Metallica" using full text search, we can do:
`yql=select * from sources * where default contains "self destruct";` and it will match.

However, we would like to be able to match any of the following queries as well:
- "self destruct metallica" (words contained in multiple fields)
- "destruct self" (inversing words)
- "hardwired self destruct" (missing the "to")
- "softwired to self destruct" (with one or more terms NOT in the document)

Basically, we appreciate the logic of the `weakAnd` operator (we are currently using `yql=select * from sources * where weakAnd(default contains "destruct", default contains "metallica");`).
But it implies that we have to tokenize the query ourselves on the client side to apply `weakAnd` between the tokens.
Additionnaly we would like to keep phrase order as well, to be weighted positively (one solution could be to add `weakAnd(..., default contains "self destruct"` for every word 2-grams in the query).

In the documentation, we found out about `userInput` that would parse the query. But none of the grammars seem to mimic the `weakAnd` effect (we couldn't find precise documentation on grammars).
Indeed, only the grammar type `any` would match all of the above queries but it seems too wide and would return too many documents.

Is there any default way of doing a flexible full text search? Could you point us to the best solution to do so?
Is using `weakAnd` a good strategy (while potentially adding n-grams in the query as well)?
If so, Is there anyway to apply the linguistic libraries on the query and then apply a `weakAnd` between the found tokens?

Thank you in advance,

Estelle

**Comment by jobergum** [comment]
For full flexibility you should consider writing a Searcher plugin (*1)  to manipulate the query tree after the query input has been parsed and tokenized. 

```
select * from sources * where ([{"grammar":any}]userQuery()); &query=
```
Solves all 4 listed matching use cases but is a straight forward OR query with the performance implications that has. nativeRank includes proximity ranking so query term order impacts the relevancy score (See (*2). 

  If you want to improve performance by using the wand algorithm instead of OR and don't have any other significant ranking signals other than text ranking you can approximate the matching phase using wand (*3) but without a Searcher you need to tokenize the user query into terms which is passed to the weakAnd arguments.  

Also the rank query operator which you calculate ranking features without impacting matching, e.g 
```
rank(
   weakAnd(default contains "foo", default contains "bar"), 
    ([{"grammar:"any", "defaultIndex":"title"}]userQuery())
 ) 
```
The above will reduce number of hits using wand algorithm using the term significance scores in the index and the top k hits (See (*3) are ranked using the configured first-phase ranking expression which will have access to rank features for the original userQuery (as passed by &query=xx) for the title field. 

(*1) https://docs.vespa.ai/documentation/searcher-development.html
(*2) https://docs.vespa.ai/documentation/text-ranking.html
(*3) https://docs.vespa.ai/documentation/using-wand-with-vespa.html

**Comment by maudetes** [comment]
Thank you a lot for your detailed answer.

To clarify our issue, we have other signals for ranking and were here only considering the first matching phase.

Indeed, using a Searcher might be the appropriate solution, although it seems rather excessive for a simple full text search. And as you said, the solution with `"grammar": "any"` doesn't match our need of performance.

Do you consider adding a `wand` grammar to the `userInput` ? It might be relevant for a simple way to use Vespa for a flexible full text search.

Again, thank you for you time.

**Comment by jobergum** [comment]
Yes, I agree that it would be nice to support passing userInput/userQuery into a weakAnd but it's also not straight forward to get all kind of use cases right. E.g the userInput and userQuery parses the query using the simple query language https://docs.vespa.ai/documentation/reference/simple-query-language-reference.html which supports also negative filters, field filters and more.

**Comment by maudetes** [comment]
Yes totally, I understand that it should not conflict with the query language support. We would be interested if this feature is implemented some day though.

For now, we are going to keep with the `weakAnd` structure with prior tokenization. And for future need, we may change for a Searcher.

Thank you again for your time, I'm closing this issue :)

**Comment by jobergum** [comment]
So maybe allow another parameter which does not support the full query syntax but which simply does best effort tokenization and stemming, without phrase support and which can be stuffed into the weakAnd for a first phase retrieval?
