### ISSUE TITLE
How to deal with multi-lang in Vespa ?

### ISSUE THREAD

**Issue by maudetes** [vespa-engine/vespa#12169]
Hello,

We have international users and documents in lots of different languages.

For example, a French user searching for "machine learning" would expect to find results in both English and French.

The detected language is English, thus stemmed as "machine learning". But it will not match any of the French documents as the French stemming of "machine" is "machin". Then no French result would be returned.

We could specify `lang=fr` but then no English documents could be matched. We could also have two queries (for French and English), but then we would have to manually merge the results.

For the first matching phase, would it be possible to use multi-lang between the preferred language and the detected language (potentially even more languages if needed) ? Then the ranking phase would decide which of the documents are the most relevant.

**Comment by jobergum** [comment]
Several approaches: 

1) Use semantic retrieval using a sentence encoder which has been trained on multi-lingual corpus like the one used here https://docs.vespa.ai/documentation/semantic-qa-retrieval.html. Sentence-Bert is another.  First phase matching is then done using ann (https://github.com/vespa-engine/vespa/issues/9747). query terms can also be passed down for fine tuning of precision. 

2) Stem and tokenize the query using the relevant languages, build a query tree using weakAnd/or and using equiv per stem variant. This is easiest done in a custom Searcher as mentioned in https://github.com/vespa-engine/vespa/issues/12154 

Using an example

lang=fr machine learning => machin learn 
lang=en machine learning => machine learn 

Using weakAnd here as example as that technique is already mentioned in the other github issue (https://github.com/vespa-engine/vespa/issues/12154 )

```
select * from sources* where rank(weakAnd(default contains equiv("machin", "machine"), default contains "learn)), default contains "machine", default contains "learning")
```
We now retrieve using all possible stems/baseforms with weakAnd and use the rank operator to pass in the original query form so that ranking can rank literal matches (original) higher. Benefit of equiv is that it allows multiple term variants to share the same position so that proximity ranking does not become broken by this approach.

**Comment by maudetes** [comment]
The second approach seems to match our needs. The only issue would be that we should detect language on the client side in order to apply the desired stemming, instead of using the processing libraries ; but as you said, using a Searcher might solve this.

Thank you for your answer, I'm closing this issue :)

**Comment by jobergum** [comment]
Thanks, to unleash the full potential you should consider doing this in a Searcher, then you get access to the Linguistic integration and programatic access to the query tree.

**Comment by jobergum** [comment]
@maudetes See https://github.com/vespa-engine/vespa/issues/13076
