### ISSUE TITLE
Geo searches don't work across the International Date Line

### ISSUE THREAD

**Issue by anguslim** [vespa-engine/vespa#12567]
We're using a `vespaengine/vespa:7.190.14` Docker container with the following search definition:

```
search testName {
    document testName {
        field latLong type position {
            indexing: attribute
        }
    }
}
```

We feed a document with `latLong` set to `"N0o0'0;W179o59'59"`, i.e. on the equator, just _east_ of the International Date Line (IDL).

Next, we perform a geo search with the following restrictions, defined in the [Vespa docs](https://docs.vespa.ai/documentation/geo-search.html#restrict):
- `pos.attribute` set to `latLong`;
- `pos.radius` set to `19970km`, which is close to the maximum permitted value; and
- `pos.ll` set to `"N0o0'0;E179o59'59"`, i.e. on the equator, just _west_ of the IDL.

We would expect to see a hit, given that the radius of the search is approximately half the circumference of the Earth, and the two given locations are practically next to each other. However, we don't get a hit.

We can't set the radius arbitrarily high as a workaround:
https://github.com/vespa-engine/vespa/blob/ea5fe1bf8c0d389a3964d2e5c490994920d21a4e/container-search/src/main/java/com/yahoo/prelude/Location.java#L130

My best guess is that the Euclidean distance is being calculated, which means the shorter distance obtained by "wrapping around" the IDL isn't being considered.

**Comment by arnej27959** [comment]
Yes - as you'll see on the map on
https://docs.vespa.ai/documentation/geo-search.html
we're just using an x/y coordinate system internally.  While this works well for most use cases it doesn't support searches across the IDL.  Since we're using an algorithmic optimization (range searches in a zcurve encoding of the x/y values) there's no easy way to fix this either.

So far, the use cases where this really matters have been few, but there's no easy workaround.
If you both
1) need to support user and queries crossing the IDL
2) don't need to use geographic search to restrict matches
you should probably just store lat/long in two numeric attribute fields, and compute distances from that.

if you need fast geo search across the IDL that's more problematic.

**Comment by anguslim** [comment]
Thanks for the quick reply! The workaround should suffice. Out of curiosity, would it be feasible to increase the maximum allowable radius of ~19970 km?

**Comment by arnej27959** [comment]
Yes, this validation isn't really necessary.  In upcoming releases you will also be able to use a negative number as radius, say pos.radius=-1 and that will translate to a range that covers all possible geographical positions.  The distance we compute will of course still be very wrong (360 degrees or 40000km) for queries that just cross the IDL, so if you have data for e.g. Fiji and Tonga - or you need a reasonable distance calculation between New Zealand and Hawaii - you'll need to find some way to handle that.

**Comment by kkraune** [comment]
Vespa releases 7.196 and higher will have this fix
