### ISSUE TITLE
Feeding document failed

### ISSUE THREAD

**Issue by quangdanh** [vespa-engine/vespa#12661]
I'm using [Vespa HTTP Client](https://docs.vespa.ai/documentation/vespa-http-client.html)  for feeding data.  But I always get the error message like this after feeding some documents:
**Result received: 212000 (1 failed so far, 221989 sent, success rate 506.34 docs/sec).**
How to deal with this issue? I have a lot of documents need to be indexed.

**Comment by bratseth** [comment]
Probably one of your documents have an error. Do you consume the responses coming back from the client? See Result.getDetails etc.

**Comment by quangdanh** [comment]
I didn't consume the result yet. I'm following the guideline to work with command line. The error message does not happen on a particular document. It seems the Vespa cannot handle it.

**Comment by bratseth** [comment]
Ok, if you use the command line the client is consuming it for you. 
The "1 failed so far" means that one operation returned unsuccessfully. 
You'll also see a line starting by "Failed: " which gives detail information about that document. What does it say?

**Comment by quangdanh** [comment]
This is error message:
```

Failure: Result for 'id:websearch:common::993908                                                        
1584366014104 Trace starting 1584366213294 Asked about retrying for cluster ID 0, number of retries is 1 
Detail:Detail resultType=FATAL_ERROR exception='A timeout occured while waiting for 'tcp/vespa-container:19101/chain.indexing' (179.996 seconds expired); Request timed out after 179.996 seconds.' endpoint=localhost:8080 ssl=false resultTimeLocally=1584366213294                  
1584366213295 Got detail: Detail resultType=FATAL_ERROR exception='A timeout occured while waiting for 'tcp/vespa-container:19101/chain.
indexing' (179.996 seconds expired); Request timed out after 179.996 seconds.' endpoint=localhost:8080 ssl=false resultTimeLocally=15843
66213294:Detail resultType=FATAL_ERROR exception='A timeout occured while waiting for 'tcp/vespa-container:19101/chain.indexing' (179.996 seconds expired); Request timed out after 179.996 seconds.' endpoint=localhost:8080 ssl=false resultTimeLocally=1584366213294                  
Mon Mar 16 13:43:35 UTC 2020 Result received: 485000 (1 failed so far, 492413 sent, success rate 564.09 docs/sec).

```

**Comment by bratseth** [comment]
Ok, so it times out. Is it this one document (id:websearch:common::993908) always timing out?
Have you looked at what it contains? Maybe something that trips up the tokenizer?

**Comment by quangdanh** [comment]
No, it doesn't happen on a particular document. That happens in sometimes. I have tried with other feed data files. But this issue still happen. It's hard to monitor which one is failed when indexing a lot of document.
Do we have any solution to handling the issue when it happens

**Comment by bratseth** [comment]
Possible causes of this are
1. you generally or intermittently have a lot of delay, due to some misconfiguration leading to full gc on intermediate nodes, very long queues, use of virtual memory or network issues.
2. some small subset of your documents take a very long time to process, perhaps triggering some tokenizatiomn issue or just being extremely large, and those have some probability of timing out.
3. some bug or condition I've never heard of before causes exactly 1 document to time out.

You should try to determine if it's 1. or 2. (or 3., but I'd say it's unlikely).
To do this, you could try to feed just a document that times out, and also investigate it.
You could also look at the average latency and the resource usage on your nodes.

If it's 1. you need to fix the issue, if it's 2. we might need to look at the behavior tokenizer and so on with this specific input. By the way, do you use a custom linguistics compnent?

It's also easy to try with a larger timeout, but I would probably want to determine the exact cause first.

**Comment by quangdanh** [comment]
1. Do you have any solution for monitoring Vespa during processing of indexing? I tried to split documents into small chunks but it still failed
2. The document failed is randomly.
3. I'm trying to gather all failed documents to reindex in another process.

**Comment by bratseth** [comment]
You can setup monitoring and monitor the relevant metrics, see https://docs.vespa.ai/documentation/monitoring.html

I would start with just looking at the resource usage on the nodes though - are any at 100% cpu during feeding? Do you use virtual memory?
Also check the log on the containers your are feeding to - do they have full gc pauses? See https://docs.vespa.ai/documentation/performance/container-tuning.html if you determine you need to tune gc.
