### ISSUE TITLE
Unclear how to create custom rank-feature

### ISSUE THREAD

**Issue by atatan-vs** [vespa-engine/vespa#13558]
Hello Vespa,

When we perform a search query, we would like to send an extra search parameter that contains a list of documentIds.
When Vespa is ranking its result, if a document happens to be in this list of ids, we would like to boost its ranking by some amount.
We have already defined a custom rank-profile but we are unclear if there is an existing rank-feature(s) we could use or if we would have to create some kind of custom rank-feature.
Can you help?

Thanks!

**Comment by bratseth** [comment]
Two ways I can think of to do this:

**1.**
- Index the id as either index or attribute, say as the field "id". Use match:exact
- Add a RankItem containing all of the document ids to boost (add it as the new root in the query, with the rest of the query as the first item and the ids to boost as the other items.
- Use the rank feature matches(id) which returns 1 if there is a match, 0 otherwise.

**2.**
- Put the id into a tensor of type tensor(id{}) as an attribute. Store the id as the single entry in that tensor, with value 1.
- Send a tensor of the same type in the query (say, boost_ids), containing one entry per key.
- The ranking expression query(boost_ids) * attribute(id) now returns 1 if the document is in the list to boost.

The first may be less work for you if you haven't worked with tensors before, and uses less memory since you can store the ids on disk.
The second is way more flexible, e.g readily allows you to set the boost value per document both in the query and the document, and will be more efficient if the list is long. It's possible to create the tensor on the fly in the ranking expression instead if you have the id already as a plain attribute.

**Comment by atatan-vs** [comment]
Thank you for your guidance, Jon!

We ended up going with Tensor approach.
After doing a lot of reading, trial and error, we have finally able to get this working.

The only thing that I'm still puzzled with is creating the tensor on the fly in the ranking expression.
We have already stored the id as a plain attribute.. but I could not find documentation example regarding on-the-fly tensor.
It would be great if you could guide us to some documentation for future reference..

Thanks once again!!

**Comment by kkraune** [comment]
Please refer to https://docs.vespa.ai/documentation/reference/rank-features.html#document-features - tensorFromWeightedSet(source,dimension) or tensorFromLabels(source,dimension)

**Comment by bratseth** [comment]
That's for multivalue attributes, for singlevalue, you can do e.g tensor(x{}):{x1:attribute(foo)}
to create a tensor on the fly. However, here it is the key you want supplied by the attribute, not the value, and that is not possible so please disregard that comment.
