### ISSUE TITLE
Normalizing rank features within query results

### ISSUE THREAD

**Issue by dingtaoliu** [vespa-engine/vespa#13698]
Apologies if this has already been asked or if I missed it in the docs.  Is it possible to normalize specific rank features across query results?  For example, I am trying to create an expression for a rank profile that combines bm25 and a popularity score.  My popularity score is normalized between 0 - 1, but bm25 is unbounded.  I want to perform some sort of normalization (e.g. min-max) on the bm25 scores from all of the query hits, but I wasn't able to find documentation on how to do so.  

Any help would be much appreciated, thank you very much!

**Comment by bratseth** [comment]
Vespa cannot do this for you. 

By "within query results" I guess you refer to finding the max (and maybe min) bm25 for the query in question and normalizing based on that? That is not possible because you need to produce a rank score during matching to determine which hits to keep on the heap, and then you don't yet know the max, and because the max may be on a different content node.

But normalizing "within query results" is the wrong approach in any case when you want to combine with features from a different "domain" than text matching. If none of the matches are good you want to know (i.e have it reflected in a lower normalized value) when combining with info from other domains.

I think you have these options:
- Determine max and min for a large set of queries and normalize at runtimne based on that.
- Use normalized text matching features instead of bm25 (you'll need to combine completeness and nativeRank/fieldMatch to get something with comparable quality).
- Machine learn a function combining bm25 and popularity to achieve some objective.
- Split into two queries (in the container), one retrieving popular items which meets a text match threshold (expressed as a rank profile) and the other retrieving by text match only (another rank profile), then blend a percentage of each.

I include the last suggestion because if popularity is measured from interactions caused by this system you are setting up a feedback loop which often leads to all results being dominated by a small fraction of your corpus.

**Comment by dingtaoliu** [comment]
@bratseth Thanks for the detailed reply! 

You're absolutely right that by normalizing text matching features and combining it with other domain features, I lose information on how good the results are textually.  Ultimately I do want to learn a function that maps all of the features into a ranking score.  I thought I could make a simple ad hoc ranking expression combining bm25 and popularity while I collect more data, but it would likely produce a worse ranking scheme if done naively. 

Thanks for your suggestion on using normalized text matching features, I'll look into learning a combination that gives similar results to bm25.  Your last point is something that I haven't considered, I'll need to introduce diversity to the results so that they aren't dominated. 

Thank you again for your help!
