### ISSUE TITLE
build vespa on debian 8

### ISSUE THREAD

**Issue by dsisds** [vespa-engine/vespa#14431]
vespa service start failed on debian server. vespa-config-sential seems be blocked. 
Vespa is built on debian 8 with  gcc 9 and llvm 7. I add -Wno-implicit-fallthrough to cxxflags to avoid Implicit fallthrough error.
Version 7.286.18 starts failed, but an old version works well.

compile error, fixed by adding -Wno-implicit-fallthrough
![image](https://user-images.githubusercontent.com/5534548/93421755-ce900b80-f8e4-11ea-9102-5b2364f5802d.png)

logs:
![image](https://user-images.githubusercontent.com/5534548/93420622-e9ad4c00-f8e1-11ea-8cdb-3aa5169d022c.png)

Process（started 10 hour ago):
![image](https://user-images.githubusercontent.com/5534548/93420661-ffbb0c80-f8e1-11ea-9996-f53e1bc7f35b.png)

**Comment by toregge** [comment]
vespa-config-sentinel is supposed to start the relevant  vespa services apart from configproxy and configserver. Before anything is deployed, this is the normal set of applications running.
If there are issues with host names in hosts.xml then vespa-config-sentinel might get an empty config after the application is deployed. Use
```
vespa-configproxy-cmd -m cache
```
to get the list of recently acquired configs through the config proxy. It should typically have a line like
```
cloud.config.sentinel,hosts/n17-020-092.byted.org,2,21f7b6121305100900463212a132ec4e
```
that shows which config was requested by vespa-config-sentinel. Use
```
vespa-get-config -n cloud.config.sentinel -i hosts/n17-020-092.byted.org
```
to get the content of that config. If it contains just 
```
port.telnet 19098
port.rpc 19097
application.tenant "default"
application.name "default"
application.environment "default"
application.instance "default"
application.region "default"
```
then this indicates that you've either got an empty application package, or that host names don't match. Normally, you should get a services array listing the services to be started by vespa-config-sentinel.

**Comment by dsisds** [comment]
I deploy an application again, but services did not start.
![image](https://user-images.githubusercontent.com/5534548/93732384-a0237080-fc03-11ea-905d-749dffb69042.png)

![image](https://user-images.githubusercontent.com/5534548/93732435-e678cf80-fc03-11ea-9c2b-4b4a0cbd4b0e.png)

here is the log file
![image](https://user-images.githubusercontent.com/5534548/93732458-03150780-fc04-11ea-841d-f3a63641f3d0.png)

no vespa services started and there is not any configproxy logs.

**Comment by toregge** [comment]
The configproxy service logs at startup and shutdown, but rarely during normal operation.
Restarting services (`sudo systemctl restart vespa`) should trigger some log entries from configproxy.

You can ask any currently running config sentinel about running services using the command `vespa-sentinel-cmd list`.
See https://docs.vespa.ai/documentation/reference/files-processes-and-ports.html and https://docs.vespa.ai/documentation/config-sentinel.html for more details.

**Comment by dsisds** [comment]
I have tried to restart vespa, but there is no extra log.
![image](https://user-images.githubusercontent.com/5534548/93998021-9a29bd00-fdc6-11ea-8318-6246bf792623.png)

The command `vespa-sentinel-cmd list ` is blocked and shows nothing.

**Comment by toregge** [comment]
The attached log shows only the first part of the restart, where the old config-sentinel receives signal 15 multiple times but has not yet stopped. configproxy receives signal 15 and stops after less than 190 ms.

**Comment by dsisds** [comment]
![image](https://user-images.githubusercontent.com/5534548/94112816-8dfe3800-fe78-11ea-8e9e-647b0042793d.png)

There is no slobrok logs in vespa.log, and no server processes started.

![image](https://user-images.githubusercontent.com/5534548/94112951-c00f9a00-fe78-11ea-8865-34d2e790d298.png)

Only configserver logs could be found in vespa.log
![image](https://user-images.githubusercontent.com/5534548/94112994-cd2c8900-fe78-11ea-9c11-82573629377d.png)

**Comment by toregge** [comment]
Since there is no log rotation (logd is not running) and vespa-config-sentinel gets a config that contains multiple services, there should be some log entries with service name config-sentinel in the vespa log after having
restarted the vespa service (vespa-config-server is running). The command `vespa-logctl -r config-sentinel` should reset the log levels for the config-sentinel service to defaults.

Some other things that might cause issues:
- Strange values for VESPA_HOME or VESPA_CONFIGSERVERS in $VESPA_HOME/conf/vespa/default-env.txt
- Multiple vespa installations on the same host  (e.g. multiple services running that don't agree on VESPA_HOME or VESPA_CONFIGSERVERS setting or network port conflicts).
- Having the environment variable ROOT set
- Having the environment variable VESPA_HOME set.
- Leftover processes from an earlier vespa installation (stop scripts don't find them based on pid files).
- Low resource limits for number of open files, number of processes, stack size, data segment size, max memory size.
- Linking with a C++ library compiled with another compiler

You might need to create an instrumented version of vespa-config-sentinel with extra logging to see why it either doesn't attempt to start services or silently fails to do so.

**Comment by kkraune** [comment]
please create a new ticket if needed, assuming this is OK, closing
