### ISSUE TITLE
Resource limits - start blocking feed operations earlier

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#14912]
When users run into [resource limits](https://docs.vespa.ai/documentation/reference/services-content.html#resource-limits) feed is blocked and clients gets a message that they need to add resources (be it disk or memory). However, adding nodes when you are already at the resource limit does not necessarily address the issue immediately as data needs to be migrated off the nodes with high resource usage so suggestion is to start blocking feed earlier than resource limit specifies.

**Comment by vekterli** [comment]
The content node already knows the origin of mutating operations (either external client load from distributors or internal mutation load from merges). We should consider adding an origin field to the SPI context or as a separate parameter to the relevant SPI methods. Proton could then look at the origin before deciding to allow or disallow an operation, maintaining two different limits internally.

**Comment by toregge** [comment]
If feed from external source is blocked at 70% full disk but feed for internal source (bucket merges) is blocked at 80% of full disk, then a multi node system might see a put first being rejected by one node but accepted by another node, causing the bucket to be inconsistent, triggering a bucket merge that succeeds due to 80% limit not yet being reached.  So we would still have an 80% limit on external load.

**Comment by toregge** [comment]
If service layer nodes reported resource usage to distributor nodes, either directly or indirectly (via cluster controller) then the distributor node could block feed from external source based on a lower resource limit before the feed operation is split up for all replicas. This would reduce the buildup of inconsistent buckets. If the distributor is able to detect ongoing data redistribution, due to a new node being added, then it could temporarily apply a slightly higher resource limit to reenable feed from external source.

**Comment by baldersheim** [comment]
You will only go above 70% for as long as all nodes are below 70. Once all nodes have reached 70% external feed will stop. But due to different merge limit the system will still be in sync, which is exactly what we want to achieve.

**Comment by frodelu** [comment]
Reset pri for reprioritization discussion (ref. VESPA-19505).

**Comment by geirst** [comment]
This has been fixed and is available in 7.370.27 (https://github.com/vespa-engine/vespa/pull/16809).

Now, the cluster controller decides whether to block external feed in the entire cluster based on resource usage sampling from content nodes. The resource limits used by the cluster controller are lower than the safeguard limits still used inside the content node (proton). The feed operations are rejected by the distributors.

Documentation: https://docs.vespa.ai/en/reads-and-writes.html#feed-block
