### ISSUE TITLE
[Question] possibility of using an indefinite number of dense vectors per document?

### ISSUE THREAD

**Issue by daouh** [vespa-engine/vespa#15794]
I would like to use Vespa to rank documents based on an indefinite number of dense vectors; I mean that a document can have an arbitrary number of dense vectors depending on the number of keywords linked to the document.  In my prototype, the final similarity measure to a query's dense vector can be calculated in different ways; for example taking the best score among the scores of all the vectors of a document. Here is my question:
 - Is there a type of fields in Vespa allowing to integrate matrices without having to predefine a fixed number of lines which would allow to have an arbitrary number of dense vectors per document but also per query?

Thank you!

**Comment by bratseth** [comment]
You can use a tensor with one mapped and one dense dimension, e.g tensor(n{}, x[500])
and then for example use the ordinal of the sentence in the document as the value of the n dimension.

This will allow you to compute the final measure however you like. If you have a lot of data you may wish for something faster than that. We're planning to support ANN for a type like this. That will be faster but you'll only be able to take the best scoring vector. The other way to do this is to use the sentences as the indexed unit instead of the documents.

**Comment by daouh** [comment]
Thank you for your return! I am going to try your first solution. I am glad to know that it you're planning to support ANN for a type like this. But in my usecase, I need to have more than one result.

I've already thought about your second suggestion, but I'm not sure it will help me. Indeed, in the case  I have a query with many vectors, I aim to compute the similarity measure of a document by computing the product of the similarity measures of each of its vectors. That means that if I have a document with two semantic dense vectors V and U, and a query with two dense vectors q1 and q2, if max (q1.U, q1.V) = q1.V and max(q2.U, q2 .V) = q2.U, the final score will be equal to q2.U x q1.V . So if I associate the vectors of a document with different indexed units, I don't see how to recombine all these scores, or I would have to use complex queries which are likely to take a long time to be executed. What do you think?

**Comment by jobergum** [comment]
>We're planning to support ANN for a type like this. That will be faster but you'll only be able to take the best scoring vector.

Yes,  a document is retrieved if any of the n vectors are in the closest top-k. Ranking will though have access to all if the doc is retrieved. Similar to what we do with array<position> and geo-search. For passage or sentence oriented embeddings for a document with > 512 tokens and a sliding window just using the centroid of the N passage embeddings a ANN index might work recall@k wise. 

Out of curiosity, your approach smells like the conformer-kernel model for text ranking? Since you are referring to infinitive numbers of embeddings which indicates to me a keyword/word level embedding and query independence assumption and not a passage/paragraph level embedding like using a bert representation model with sliding window.

**Comment by bratseth** [comment]
> What do you think?

Yes, ANN may not be of much help here, since it will still require a single query vector and will surface the documents with the lowest distance between two vectors, not q2.U x q1.V. As Jo Kristian points out you can still compute this as the final (or, phase 1 really) score, but you won't surface all the right candidates.

Just to mention one more thing: We have recently made a lot of work on improving performance with mixed tensors like tensor(n{}, x[500]), so if you care about performance at this stage make sure you have a very recent Vespa release.

**Comment by geirst** [comment]
The performance improvements of mixed (and sparse) tensors are part of Vespa 7.319.17 (25-Nov-2020).

**Comment by daouh** [comment]
Hello! Thank you all for your reply!


> The performance improvements of mixed (and sparse) tensors are part of Vespa 7.319.17 (25-Nov-2020).

That's cool ! I will then install the latest version of vespa!

 > We're planning to support ANN for a type like this. That will be faster but you'll only be able to take the best scoring vector.

Perfect! and do you know by when is will be available?

> Yes, a document is retrieved if any of the n vectors are in the closest top-k. Ranking will though have access to all if the doc is retrieved. Similar to what we do with array and geo-search. For passage or sentence oriented embeddings for a document with > 512 tokens and a sliding window just using the centroid of the N passage embeddings a ANN index might work recall@k wise.

I see how it's working thank you for details! 

> Out of curiosity, your approach smells like the conformer-kernel model for text ranking? Since you are referring to infinitive numbers of embeddings which indicates to me a keyword/word level embedding and query independence assumption and not a passage/paragraph level embedding like using a bert representation model with sliding window.

Yes we start from the same assumptions as conformer-kernel model with keywords level embeddings. But with simple calculations!

> Yes, ANN may not be of much help here, since it will still require a single query vector and will surface the documents with the lowest distance between two vectors, not q2.U x q1.V. As Jo Kristian points out you can still compute this as the final (or, phase 1 really) score, but you won't surface all the right candidates.

What if I use brute force? I know it won't be fast but I will be able to have the right relevance computing this as the final score?

**Comment by bratseth** [comment]
> do you know by when [ANN for multiple vectors per document] will be available?

I'd say it's currently a fair chance we'll prioritize this in Q1.

> What if I use brute force?

Yes, that will work fine. And since you can parallelize as much as you want you can get as low latency as you want (down to about 10 ms average or so at least), but it may be too costly.

**Comment by daouh** [comment]
Perfect! It's pretty clear to me! Thank you!
