### ISSUE TITLE
[FEATURE REQUEST] Add CREATE operator to PUT operations

### ISSUE THREAD

**Issue by jnioche** [vespa-engine/vespa#16209]
I am trying to index documents using the Vespa HTTP client. One thing I need to do is to create some of these documents only if they don't already exist. They must not overwrite an existing version. Other documents (the minority) will be allowed to overwrite.
I see that there is a CREATE operator but it sounds like it applies to UPDATEs only, whereas I'd need them for PUTs. Using them on UPDATEs would create them if they are not present but would also overwrite an existing document with the same ID which is definitely what I want.

I suppose the default value would be true i.e put something even if there is no doc with that ID. A value of false would prevent overwriting.

**Comment by vekterli** [comment]
Conditional Put operations combined with `create` are now supported (since Vespa 8.178).

This should enable the use case you outlined, i.e. specifying a condition of `false` that will be ignored if (and only if) the document does not exist.

Documentation:
 * [Semantics of conditional put+create](https://docs.vespa.ai/en/document-v1-api-guide.html#conditional-updates-and-puts-with-create)
 * [Document V1 API JSON](https://docs.vespa.ai/en/reference/document-json-format.html#create)

**Comment by jnioche** [comment]
that's great thansk @vekterli
