### ISSUE TITLE
Use operator EQUIV instead of OR cost more cpu usage ?

### ISSUE THREAD

**Issue by luoyetx** [vespa-engine/vespa#16224]
According to Query Rewriting document section [here](https://docs.vespa.ai/en/query-rewriting.html), I test the yql below

```
select * from index where field contains "A" or field contains "B";
```

```
select * from index where field contains equiv ("A",  phrase("B", "C"));
```

When using the second yql, the cpu usage become much higher than the first one. Is it normal and how to reduce the cpu usage?

**Comment by luoyetx** [comment]
The vespa version I use is 7.0

**Comment by jobergum** [comment]
If you compare apples versus apples and comparing or with equiv with the same type of query terms I believe the performance should be roughly the same as measured by latency and cpu util

This is an apple versus apple comparison where we replace OR with equiv which acts as an OR for retrieval but threats the two terms as equal during ranking. 

This is an apples versus apples comparison:

```
select * from index where field contains "A" or field contains "B";
```
and compare with 
```
select * from index where field contains equiv("A","B");
```
I expect latency and cpu util to be comparable. 

This query however introduces a phrase term which changes the complexity:

```
select * from index where field contains equiv ("A",  phrase("B", "C"));
```
The above involves a phrase term which is more costly to evaluate as positions of term B and C needs to be intersected which involves more cpu processing.

**Comment by bratseth** [comment]
So, in conclusion using a phrase is inherently more expensive and you need to consider if it is worth it for you. 

An alternative could be to search for A or (B and C) and do the more accurate processing as ranking (by using a ranking function where  documents with B adjacent to C get a higher rank score).

**Comment by luoyetx** [comment]
@bratseth @jobergum Thanks for you reply. As I mentioned in https://github.com/vespa-engine/vespa/issues/15876, the OR and EQUIV behave different when calculating features/scores. Any way to implement like equiv (A, B and C) which doesn't requires the positions?

**Comment by jobergum** [comment]
HI @luoyetx, could you be more specific here with examples? I'm confused so please be patient :)

It's correct that (A OR C) produces different feature score for multiple ranking features (e.g nativeRank(field), bm25(field)) than equiv(A,C). 

 I don't see the connection with #15876 directly since it did not not mention equiv but repeating a term several times. 

>Any way to implement like equiv (A, B and C) which doesn't requires the positions?

The amount of information loaded from posting lists depends on the ranking features which are used in the ranking profile, but phrase search will always need to load position information from postings lists.

**Comment by luoyetx** [comment]
@jobergum sorry for the confusion, let me explain a use case.

If we rewrite term "cat" with "hello kitty", what we want to retrieve is the document with term "cat" or terms "hello" and "kitty"(the distance  between these two terms should be 0). If we use `title contains "cat" or title contains phrase("hello", "kitty")`, the score of the document(only with term "cat") can be smaller then `title contains "cat"`(mentioned in #15876 ). So we use equiv instead of or. the yql becomes `title contains equiv("cat", phrase("hello", "kitty"))` and the cpu usage is unacceptable. (we didn't test the cpu usage of first yql, maybe it also increase a lot of the cpu usage)

As @bratseth said, the `phrase` harms the  performance, actually for term "hello" and "kitty", ignore the distance when matching is acceptable, if we retrieve a document with title "hello xxx yyy zzz kitty", we can manually design some distance feature and using ranking model to deal with the problem. So I ask for a way to implement something like `equiv("cat", "hello" and "kitty")`.

**Comment by jobergum** [comment]
Thanks for the clarification and sorry for the late reply. 

> If we use title contains "cat" or title contains phrase("hello", "kitty"), the score of the document(only with term "cat") can be >smaller then title contains "cat"(mentioned in #15876 ).

Could you clarify the problem here. It's also unclear what exactly score you mean? Are we talking about nativeRank? In this case yes, the score is different but this is ranking which is ordering results and the two queries are different in the case where you use OR documents with both cat and "hello kitty" will be *ranked* higher. It's also unclear if the increased cpu usage is related to this change, if you track total number of hits and this increases after this change then it could be explained as doing query expansion either by OR or using equiv might increase the total number of hits. 

I don't have a clear simple solution to this, but I'll give a few thoughts on this. 

So rewriting the query in this way classifies as query expansion which I believe you do to try improve recall as you metadata per video is limited. The alternative to query side expansion is document side expansion which is cheaper. An interesting approach for document side expansion is document to query using a sequence to sequence generative model (e.g T5) which predicts queries for the given document text.  See e.g https://github.com/vespa-engine/sample-apps/tree/master/msmarco-ranking and how we train a LightGBM model combining multiple features over matching in multiple fields and where the expanded document queries are indexed in a separate field and where we use features like elementCompletness in the trained expression. I think that your organization have a lot of experience with ML and lots of training data so this might be an alternative to rule based query expansion to improve recall. 

It is not possible to do equiv("cat", "hello" and "kitty") as equiv only works on terms and phrases and I don't see a work around to other than in the index use a query expansion field using word/exact matching to avoid phrase search.

**Comment by jobergum** [comment]
Couple of examples using MS Marco Passage Ranking dataset

The phrase "hello kitty" occurs in 138 passages
![image](https://user-images.githubusercontent.com/20928528/106466409-935d3600-649b-11eb-9d73-ecc043fdbdc5.png)

Expanding "hello kitty" with the more general "cat" using OR brings the total hit count to 47440 passages, this increase in number of hits which is exposed to ranking does impact serving performance. 

![image](https://user-images.githubusercontent.com/20928528/106466586-cf909680-649b-11eb-8afd-82aae2d128c8.png)


Both examples uses bag of of word BM25. Similar if using equiv the total number of hits increases, phrase or not so this might be the reason you see performance impact but difficult to assess based on the information to this ticket.

**Comment by luoyetx** [comment]
@jobergum Thanks for your detail reply. We already use OR instead of equiv, so i believe the performance is harmed by phrase. The score returned is based on nativeFieldMatch (seems not much difference with nativeRank). Why we need the score to be comparable is because we want to get multi query result and rank them with a limited number.

You also mentioned the document side expansion, but i believe it's easier to expanse query side because you don't need to update all documents when updating the generative model.

Thanks for your kindly reply, we may need to modify the score calculation logic by ourself to satisfy the demand.

**Comment by jobergum** [comment]
Oki, using BM25 which is also a bag of words model is slightly faster than nativeFieldMatch ranking feature but the phrase constraint is the same. 

I have also earlier talked about retrieval using weakAnd which also can be combined with the rank() operator to production additional features and where those features are not evaluated. 

rank(weakAnd(,..), phrase(,...)) will be faster as the phrase term in this case will only be evaluated for those documents making it into the top-k result of the weakAn
