### ISSUE TITLE
Clarity about how filtering works with ANN

### ISSUE THREAD

**Issue by SaiKiranBurle** [vespa-engine/vespa#16499]
Hello, I'm exploring the usage of Vespa for large scale Recommender systems where we need to find nearest neighbors in a large space, while being constrained by metadata filters.

I have read the blog post (https://blog.vespa.ai/approximate-nearest-neighbor-search-in-vespa-part-1/) which discusses some interesting aspects about this work. At the end of the post, you mention that there are tradeoffs between using approximate and exact search based on how many documents are filtered away.

I also came across this post (https://towardsdatascience.com/using-approximate-nearest-neighbor-search-in-real-world-applications-a75c351445d) which mentions

> If the eligibility list is small in relation to the number of items in the graph, skipping occurs with a high probability. This means that the algorithm needs to consider an exponentially increasing number of candidates, slowing down the search significantly. To solve this, Vespa.ai switches over to a brute-force search when this occurs. The result is a very efficient ANN search when combined with filters.

This is very interesting, but I could not find any other references to this implementation that dynamically switches between exact and approximate. Can you point me to any documentation or code that achieves this behavior?

**Comment by geirst** [comment]
When using the _nearestNeighbor_ operator together with other query filters we first calculate a _global filter_ bit vector in the match evaluation. This evaluates the query (excluding the _nearestNeighbor_ operator) as cheaply as possible using termwise evaluation and bit vectors where possible. The result contains the local document ids of those documents passing the filters of the query. We then use this _global filter_ when setting up the _nearestNeighbor_ operator for execution. If the number of documents in the _global filter_ is less than 5% of the total number of documents on that node, we choose to evaluate exact instead of approximate, as that becomes cheaper. This number was chosen based on experiments with the 1M SIFT and GIST datasets.

The fallback to exact evaluation happens in NearestNeighborBlueprint::set_global_filter():
https://github.com/vespa-engine/vespa/blob/master/searchlib/src/vespa/searchlib/queryeval/nearest_neighbor_blueprint.cpp#L109

**Comment by SaiKiranBurle** [comment]
Thank you. That clarifies my question.
