### ISSUE TITLE
Using BERT and Tokenizers in vespa + some recsys db questions

### ISSUE THREAD

**Issue by simeneide** [vespa-engine/vespa#17197]
Hi, I gave vespa a first go and have some questions. In general it looks quite easy to get started with "standard" search models. My use case is to create a search app that uses a custom huggingface BERT model and tokenizer trained on custom data. The model is used to produce a vector that I want to do ANN. I am mainly following the Q-A sample app (https://github.com/vespa-engine/sample-apps/tree/master/dense-passage-retrieval-with-ann).

**Question 1: using tokenizer+bert model**
Feeding of documents seems fairly fine, and I guess I can just use the huggingface pipeline to featureize the documents. (although the example app is using pre-computed vectors from the researchers here, you might want to make this explicit as practicioners seldom have a research team that have precomputed the vectors ;) ).

However, using BERT in the application seemed a bit more complicated, and in specific the tokenization. It seems like you have implemented your own java-tokenizer that (hopefully?) replicates the huggingface-tokenizer. I did spend some time realizing this and I still dont fully understand how that plugin works.
I feel a more natural workflow is to be able to use the huggingface pipeline directly in vespa (or the tokenizer+onnx model). Now I feel that the bert-model is "floating" all over the place in the serving code, making many possible areas of failure. Having the full model code bundled into one "package" would make it easier to redeploy if I am retraining the model every night, or have multiple models deployed. 
Is this possible in some way? Or is it discouraged for some reason?

**Question 2: Multiple models**
If I have multiple models (e.g. I have trained two matrix factorzation models with user- and item vectors). What is the best practice of adding these to vespa? Is it to have separate Fields in the user-schema like this?

```
Field(name="model_1_vector", ...), 
Field(name="model_2_vector", ...)
```

And if I have a system that retrains these vectors every night, should updates of the model be handled by updating these vectors, or creating new fields and deleting the old ones? E.g. that a field is both model and version of the model?
```
Field(name="model_1_vector_version_25march2021", ...), 
```

**Question 3: Use vespa to update a user state - e.g. the last 10 clicks of the user**
If I want to keep track of the last 10 clicks of the user (to use in e.g. an autoregressive recommender system), is this something I can/should do with vespa? If yes, is the best approach to have a separate field in the user schema and then query + update it in a feeder? something like this:

```
old_vec = app.get_data("exercise",11).json()['fields']['click_sequence']
new_vec = some_function_that_updates_vector(old_vec, new_click)
app.update_data(schema="user", data_id="11", fields={"click_sequence" : new_vec})
```

Thank you :)

**Comment by jobergum** [comment]
Thanks a lot for the great questions and feedback @simeneide.

> Question 1: using tokenizer+bert model

For offline processing/tokenization/vectorization/model evaluation Vespa does not offer any advantages as a platform compared to running Huggingface transformer pipelines with large batch sizes, preferably using GPU. So in this case we just used the precomputed vectors. 

Yes, there is a BERT tokenizer written in java which is compatible with the huggingface version  If it was not we would not be able to reproduce the EM and retriever scores. The tokenizer is a "generic" component which is injected and available for document processors and searchers. It takes the vocabulary as input.  Some of the reasoning why model and tokenizer is separated:

- We want to tokenize the document at ingestion and store the tensor representation in the document in memory for quick access at query time. 
- The BERT model is represented in ONNX format and we use ONNX-RT for fast(er) evaluation of ONNX models. ONNX only represent the compute graph and tokenization is not part of ONNX representation.   
- In the serving architecture of Vespa we move the computations close to the data on the content nodes where the ONNX model is (along with all other ranking and search features of Vespa). The BERT query tokenization is done once at the stateless container so the tokenization is not re-done at every content node involved in the execution. 

So there is a tradeoff here between easy of use and end to end serving performance in a scalable way but agree that it can be confusing if you are used to huggingface pipelines where tokenizer and model is more tightly coupled.  

If you plan on changing the embedding model frequently you can have multiple fields in the item document type. Vespa supports multiple fields that are setup for HNSW (to support fast ANN). You can use partial updates to feed the new version tensors without having to feed everything else. 

>Question 2

For the user doc you could have versioning by using a mixed tensor but if you plan on any time change the dimensionality for the dense representation you need multiple fields, or use sparse as this is not directly used for serving but only read. 

{code}
field user_embedding(version{}, x[100]) {}
{code}

> Question 3

You can store this user data as well as a mixed tensor, and you can update tensor cells (add, remove, assign) so you do not need to read the entire blob and apply the update and feed the version back.  See https://docs.vespa.ai/documentation/tensor-user-guide.html for an intro to tensors and operations on tensors. But there is no logic for last x etc so that is application specific.

**Comment by bratseth** [comment]
Minor typo, you mean `field user_embedding type tensor(version{}, x[100]) { ... }`

**Comment by simeneide** [comment]
Thank you, Ive started implementing a search engine with these questions in mind. I am sure there will be additional issues, but thank you so much for good replies :)

For the onnx-runtime and tokenization: I found that for now I just do all the featureizing in the app built outside vespa, and then just use the tensor capabilities of vespa. Kind of unfortunate, but it allows me to keep tokenizer and bert-model in one place. A feature request would be to allow huggingface-pipelines as "one package" (and then vespa could split the pipeline however it wants), but I realize that is a tight integration to huggingface.
