### ISSUE TITLE
support state-considering rank

### ISSUE THREAD

**Issue by yehzu** [vespa-engine/vespa#17392]
In the e-commerce domain, a product is usually stored as a Vespa document. 
A product usually has a series of promotions and corresponding effective dates and promotion prices.
We want to sort products by their promotion price. However, we need to feed all the promotion info in advance because it is impossible to feed the promotion price at the moment the promotion takes effect. 
Therefore, a product would look like
```
document product {
        struct promotion {
            field id type string {}
            field startTime type long {}
            field endTime type long {}
            field price type double {
        }

        field promotions type array<promotion> {
            indexing: summary
            struct-field id { indexing: attribute }
            struct-field startTime  { indexing: attribute }
            struct-field endTime  { indexing: attribute }
            struct-field price  { indexing: attribute }
        }
}
```

Currently, due to limited programmability in rank profile, if we want to sort by active minimal promotion price, the rank profile have to be written like this:
```
rank-profile promotionPrice {
   rank-properties {
      $defaultMax: 9999999999
   }
  function activePrice(index) {
    expression {
      if (attribute(promotions, index).startTime < now,  if (attribute(promotions, index).endTime > now, attribute(promotions, index).price, $defaultMax) ,$defaultMax)
    }
  }
  function minPrice {
    expression {
      min(activePrice(0), min(activePrice(1, min(activePrice(2, $defaultMax)))))  // manually for-loop
    }
  }
  first-phase {
    expression: minPrice
  }
}
```
The problem is that we need to manually expend the for-loop with a fixed index. If promotions size larger than the fixed index, then the rank would not work.
Hope that there is a feasible and elegent way to achieve this requirement.

**Comment by kkraune** [comment]
Great question! I don't have the complete solution, but I suggest looking into using a tensor, as tensors can be reduced using a min aggregator over a dimension: https://docs.vespa.ai/en/reference/ranking-expressions.html

**Comment by bratseth** [comment]
To do this, create three separate tensors in the document, for startTime, endTime and price, all with a single mapped dimension with promotion id as the label.

```
  field startTime type tensor(id{}} {
      indexing: attribute
  }
  field endTime type tensor(id{}} {
      indexing: attribute
  }
  field price type tensor(id{}} {
      indexing: attribute
  }
```

Now your documents can set promotions as entries in these three tensors, e.g

```
startTime = {promo1:40, promo2:60, promo3: 80} 
endTime   = {promo1:50, promo2:70, promo3: 90} 
price     = {promo1:16, promo2:18, promo3: 10} 
```

(where 40 etc. should be actual timestamps of course).

With this, the ranking expression

`(startTime < now) * (endTime > now) * price`

will produce a tensor(id{}) which has the correct price if its currently valid and 0 otherwise. (To see why, refer to https://docs.vespa.ai/documentation/reference/ranking-expressions.html).

If you don't have overlapping promotion intervals (so that you need to take the lowest non-zero), all you need to do is take max from this tensor: max(...).

If you may have overlaps, you should map each 0 to a max value first: map(..., f(price)(price == 0, 9999999999, price), and then take min of that.

**Comment by yehzu** [comment]
Cool! I will have a try!
How about the performance? Is it a relatively heavy rank operation?

**Comment by bratseth** [comment]
Should be fine unless you have very many promotions, then you'll feel the cost of joining over the id dimension.
