### ISSUE TITLE
Raw document fields "decoded" on retrieval

### ISSUE THREAD

**Issue by kaplanjs** [vespa-engine/vespa#17668]
When base64 encoded data is fed to a `raw` type field of a document (for example `"KGxwMApTJ2EnCnAxCmFJMgphKGRwMgpJMQpJMApzYS4="`), the data is base64 decoded before being retrieved (producing in this example `"(lp0\nS'a'\np1\naI2\na(dp2\nI1\nI0\nsa."`). I have verified via the V1 Document API that the encoded data is stored as-is, and is only decoded during retrieval. Importantly, I have found in my own application that the decoding sometimes converts to escaped unicode (for instance `"\\x80\\x03]q\\x00X\\x07\\x00\\x00\\x00contextq\\x01a."` instead of the original string `"\x80\x03]q\x00X\x07\x00\x00\x00contextq\x01a."`), making it a challenge to recover the original data. To my understanding, the data fed to any document field should be returned in the exact format in which it was uploaded.

This issue can be minimally reproduced via updating any of the sample app document schemas with a raw field and updating the corresponding sample data feed accordingly, and then running the sample app with any query. I have made [a PR to the sample-apps repository](https://github.com/vespa-engine/sample-apps/pull/525) modifying the blog-search sample as described above to reproduce the issue. This PR is not meant to be merged, but is there so that the changes can be checked out for ease of reproducibility.

**Comment by kkraune** [comment]
From another ticket on the same issue:

> The container will represent the value of a raw field as an instance of com.yahoo.prelude.hitfield.RawData.
The JSON renderer has no code for handling this and falls back to calling Object.toString, which in the case of RawData returns a string containing each byte as its ASCII character representation if (roughly) a printable ascii character and a hex number prefixed by "\x" otherwise. This is why you see the string value of the bytes "Unknown artist from the moon", there is no conversion prior to rendering and another renderer could do something else.

While discussing this matter, we found that we cannot change the query result rendering without possibly breaking existing applications. I assume you refer to the Vespa Query API here: "that the decoding sometimes converts to escaped unicode"

I think a workaround making a customer renderer: https://docs.vespa.ai/en/result-rendering.html

**Comment by kaplanjs** [comment]
This makes sense for data uploaded directly, but I'm encoding to base64 before uploading and the returned content is no longer base64 encoded. That can't be caused by the call to Object.toString, can it?

**Comment by baldersheim** [comment]
Looks might be deceiving :)
1 - Input of raw fields with json. We require input of raw fields to be base64 encoded. We Base64 decode and they are represented as binary data inside vespa.
2 - When fetching the documents via document/v1 or vespa-get or vespa-visit we Base64 encode the binary data so that you see exactly what you put in. But not how it is really stored.

3 - But then it is the problem you see, When you want to look at the field when searching via a summary class we are NOT giving you Base64 encoded data, but instead an escaped byte sequence of the binary data. And this is the API we can not break, even if it is confusing and wrong.

We will most likely solve this by adding a config override for this behaviour that defaults to current, but that you can override to have Base64 encoded summaries for raw fields. Then the default will be flipped on Vespa 8.
I expect us to get at this one by the end of the month.

**Comment by baldersheim** [comment]
Suggestion is to add `raw-as-base64-in-summary` as keyword for triggering base64 encoded summaries under the `schema` level

**Comment by baldersheim** [comment]
This is present in 7.407.3 and on.
