### ISSUE TITLE
Complete Unicode support for linguistic processing and indexing

### ISSUE THREAD

**Issue by gekirabu** [vespa-engine/vespa#18001]
It seems that vespa does not completely support Unicode indexing and retrieval right now, only alphabetic and numeric characters are considered to be [`isIndexable`](https://github.com/vespa-engine/vespa/blob/master/linguistics/src/main/java/com/yahoo/language/process/TokenType.java#L28-L41).

I've encountered this issue while playing with Emojis, searching for `😊` will simply get rejected with a `400 Bad Request`. Searching `😊a` is allowed but unfortunately the results are only about `a` since the Emoji code points were stripped.

Actually it is still unclear to me which code points are invalid as the comments in [`TokenType`](https://github.com/vespa-engine/vespa/blob/master/linguistics/src/main/java/com/yahoo/language/process/TokenType.java#L30) noted:
> Note that a Token can be excluded from an index, even though the token type marks it as indexable.

Further testing revealed that besides Emojis, a wide range of codes points were excluded while indexing. I would suggest to preserve all Unicode code points throughout linguistic processing and indexing, as it would increase adoption of vespa in domains like conversation searching (which requires Emoji) and technical document indexing (which even the `U+FFFD` replacement character is meaningful).

**Comment by bratseth** [comment]
The tokenizer in Vespa turns text into tokens that are indexed and used for queries. There are two aspects to this: Deciding what characters should be included as indexable tokens, and deciding the token boundaries. These decisions impact recall and precision, as well as performance.

For example, if we indexed every period sign as a separate token, we would create a much larger number of tokens, and any query which included a period would in effect retrieve the entire index. Or, if we indexed periods as part of the preceding word, we would not retrieve any document which happened to have that word as the last in a sentence. For this reason it is not in general a good idea to just preserve all code points (and it doesn't even have one unique meaning).

Regarding emoji's - the default tokenizer does not classify them as text tokens for indexing. This can be changed by plugging in a custom tokenizer, but should it be changed in the default? Do you know of a real use case where people want to retrieve only the documents that contains a specific emoji?

**Comment by gekirabu** [comment]
> For example, if we indexed every period sign as a separate token, ... Or, if we indexed periods as part of the preceding word, we would not retrieve any document which happened to have that word as the last in a sentence.

For the specific case of period signs (and other ambiguous punctuations), I would suggest to follow the [Word Boundary Rules](https://unicode.org/reports/tr29/#Word_Boundary_Rules) in Unicode® Standard Annex #29.

> ... we would create a much larger number of tokens, and any query which included a period would in effect retrieve the entire index... For this reason it is not in general a good idea to just preserve all code points (and it doesn't even have one unique meaning).

We used to implement our in-house information retrieval system with index-time pruning based on [Inverse document frequency](https://en.wikipedia.org/wiki/Tf–idf#Inverse_document_frequency_2). Basically we assume punctuations will have low IDF weights and cut them off just like stop words in large text fields (e.g. body), while preserving a limit amount of them in significant text fields like titles. This might lead to index format changes since we have to count the frequency of a token while not actually indexing it. I think we could take a simpler approach: maybe just allow the users to enable full Unicode in specific fields in their schemas?

> ... but should it be changed in the default? Do you know of a real use case where people want to retrieve only the documents that contains a specific emoji?

We've been testing with a dataset of social network dumps, the original platform allows users to use display names with arbitrary Unicode characters, so that `Elon` and `Elon ♐️` are two unique users.

Actually I think emoji is only the tip of the iceberg, adding support for all Unicode planes is more of a future-proof enhancement. Here's a real world example: The Unicode Consortium reserves code points for [eras in the Japanese calendar](https://en.wikipedia.org/wiki/Japanese_era_name), but the latest `㋿ U+32FF` announced on 1 April 2019 is not a subsequent of the previously used block of `㍻ U+337B` - `㍾ U+337E`. Although I'm not Japanese but I'm aware that they use these Unicode graphemes in official documents and formal writings to distinguish `㍼24年` (AD 1949) vs `㍻24年` (AD 2012).

I understand that Unicode might not be a first class citizen in languages with latin-script writing systems, but languages of the world are so diverse, the Chinese are basically writing in "emojis". Vespa is such a wonderful piece of technology and enhancing Unicode support will definitely bring more diversity to the community.

**Comment by bratseth** [comment]
> For the specific case of period signs (and other ambiguous punctuations), I would suggest to follow the Word Boundary Rules in Unicode® Standard Annex #29.

I can't even understand if that recommends keeping "foo." together or not, but in any case this must be decided by the tokenizer (which by default is OpenNLP), not Vespa. 

Using IDF to determine indexing would have a least three problems: We need to track it when not indexing (as you say), non-indexable characters can be low frequency (e.g ";"), and indexable may have high frequency (say, "the" - we still want to match "the the").

> Elon and Elon ♐️ are two unique users

For user names you should not use text matching but instead match:exact, which just matches all the characters exactly (including whitespace). If you want that, but not whitespace, you can use match:word instead. See https://docs.vespa.ai/en/reference/schema-reference.html#match
(You might also want to make these attributes instead of index so that you can group on username etc.)

FYI, all of this is not related to unicode in itself - Vespa uses unicode everywhere.

CJK characters are classified as text (in contrast to emojis), but here the problem is that you need a tokenizer that segments the text into probably-correct tokens. OpenNLP does not do that so you need to plug in another tokenizer for that.
However, segmentation of CJK in queries is unreliable due to the lack of context, so it will always cause recall issues. I recommend using n-gram instead for CJK, in combination with a rank function that incorporates position info (such as e.g nativeRank).
