### ISSUE TITLE
Improve allocation strategy for link arrays in HNSW index to reduce wasted address space

### ISSUE THREAD

**Issue by geirst** [vespa-engine/vespa#18153]
In #18124 we observed running out of address space for the link arrays in the HNSW index. The link arrays are stored in an ArrayStore using 32-bit references. This maps to 1024 buffers, each supporting up to 4 MiB of separate arrays of a given size. The theoretical max number of link arrays is 4 GiB, which match the max number of documents on a single node.

However, the way these buffers are allocated we might end up hitting the address space limit much sooner. A buffer in the ArrayStore is resized several times until it can store 64 KiB of arrays (of a given size). When we later need more capacity for that array size we allocate a new buffer. The grow factor when allocating a new buffer is 20%, so it takes several buffer allocations before we reach the max capacity of 4 MiB of arrays in a single buffer.

In #18124, the number of arrays of various sizes (1 - 64) were spread evenly across the 1024 buffers, meaning each array size used ~16 buffers. When these buffers only end up storing around 64 KiB of arrays, the max number of arrays available is only 64 MiB. It stopped at 59.3 million link arrays (and documents). We have increased this limit to 512 MiB (#18150) and the grow factor to 30% as a short term improvement. This is part of 7.416.11.

In addition we should improve the allocation strategy in the ArrayStore to better utilise the full 4 GiB address space. This could be re-sizing a smaller buffer for a given array size instead of allocating a new buffer.

**Comment by toregge** [comment]
Changes to avoid crash:
- Take grow strategy into account when switching from non-first buffer for a type to a new buffer. This enables earlier ramp-up of buffer sizes.
- Resize the smallest buffer for a type if it can grow if there are 4 or more active buffers for that type instead of just switching to a new buffer. This reduces the number of small buffers.

Changes to use less memory when max-links-per-node value is larger than 32:
- Configure the ArrayStore used to store arrays to handle larger arrays before falling back to indirect storage. Currently, we use vespalib::Array for each array that has more than 64 elements.
- Use more than 10 bits of EntryRef to specify buffer for the ArrayStore used to store the link arrays. This enables more buffers per array size. Max buffer size is reduced accordingly.

Change to use less memory when number of documents on the node is reduced:
- Add support for compaction.

**Comment by toregge** [comment]
This is now included in vespa 7.454.27 and newer.
