### ISSUE TITLE
Return query errors detected by proton in the response 

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#18591]
Query errors detected in proton are logged instead of returned in the response due to the old query protocol not easily supporting passing them in the response. Since the old protocol is gone we should fix this.

**Comment by havardpe** [comment]
Ironically, the ability to report errors through the top-level search API implemented by proton was removed when support for the old transport protocol was removed; the old protocol supported error reporting while the new protocol does not (yet).

Error reporting in the new protocol was postponed since there was no obvious one-true-way of reporting errors and it would be easy to add later (later being now, I suppose).

How should errors be reported in the search reply? list of strings? something more 'semantic'? I expect we want to be able to report multiple errors and convert them to ErrorHits added to the result in the container or similar.

What specific error(s) should we report? Some errors will probably be harder to extract than others due to internal abstractions. I propose we start with something useful yet limited.

**Comment by bratseth** [comment]
Really? Can't recall even implementing that at the Java side.

I think a list of strings are fine, attempts at semantics doesn't ever seem to do much difference. 
Or maybe list of objects of strings to leave the possibility for more open.

We discussed doing this for just one error to get it this working end to end, then it should be much less effort to do others incrementally later. We could do e.g the one in https://github.com/vespa-engine/vespa/issues/18590

**Comment by arnej27959** [comment]
this was implemented in a recent work package ("issue" reporting).
