### ISSUE TITLE
Add stateless model evaluation parameters  

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#19084]
### Motivation

For ONNX models we would like to be able to control number of intra and inter threads, and possible execution mode on a *per model* basis. The motivation behind this feature request is https://github.com/vespa-engine/vespa/issues/18882#issuecomment-917682562. The default intra-thread setting of ONNX-RT is to use all available threads which just leads to trashing and a *slower* inference than using e.g just 2 threads. For smaller models with short input sequence length we just want to use 1 thread, for larger model with larger batch/sequence length one would like to use more. 

### Syntax Suggestion
In the example below one can also add a model name so that one can use "/model-evaluation/v1/ranker/" in the path instead of the file name of the model. Syntax proposal:

```
<model-evaluation>
  <models>
    <onnx>
       <model name="ranker" file="models/reranker_marging_loss_v4.onnx">
         <settings>
          <intra-threads>4</intra-threads>
          <inter-threads>4</inter-threads>
         </settings>
       </model>
    </onnx>
  </models>
</model-evaluation>
```

This syntax could also be later be expanded to tie a specific Tokenizer (https://github.com/vespa-engine/vespa/issues/18881) to the model if the input to the model is text to transform the text into the tensor input to the model. 

### Other
Note that model-evaluation also supports XGBoost and LightGBM but afaik they don't have any run time settings of huge interest as they are converted to a vespa ranking expression.

**Comment by bratseth** [comment]
Yes, this makes sense, but not sure what you mean by intra-threads here? Afaik there's just one value to meaningfully set here and we could just call it "threads"?

I don't think we need <settings>? It's all settings ...

It's probably also useful to be able to set a default across all models, i.e right under <models>.

And I think the default default should be 1 not "all"?

**Comment by jobergum** [comment]
Intra-threads is a ONNX-RT specific (Also present in Tensorflow etc) where it attempts to speed up inference by using more threads when evaluating the ONNX graph. Below is obtained with 1 benchmarking client (no concurrency). The default setting is unfortunately attempting to use threads equal to processors available. 

There is both intra-threads and inter-threads in ONNX but the latter is only relevant if execution mode is parallel, for know the most important thing is intra-threads, and we could let <threads> mean setting both intra and inter to the same. 

![image](https://user-images.githubusercontent.com/20928528/133042098-ad83e760-ce4f-4690-b1f8-57446bd200cb.png)

**Comment by jobergum** [comment]
So you are right, as long as we don't expose execution mode (parallel versus sequential) we can collapse the parameter to threads. It's hard enough to understand what intra versus inter, me and @lesters are going in circles still about it :)

**Comment by jobergum** [comment]
The syntax could also be extended to specify if to use GPU or CPU provider per model basis once https://github.com/vespa-engine/vespa/issues/14406 is completed.

**Comment by lesters** [comment]
Well, it makes sense to keep the two settings separate. It's important to note that these are intra-**operation** and/or inter-**operation** thread pools. An **operation** is for instance a matrix multiplication, a reduce etc. 

Inter-op threads is the number of threads available for running multiple operations in parallell. This is only applicable for execution mode (another setting) parallel, and useful for models that have largely independent paths, e.g. a two-tower model that has two sub-models that are independent, and only joined in the end.

On the other hand, some operations have multi-threaded implementations. The intra-op threads is the number of threads available for running these. The work done in some operations can be significant and a good multi-threaded implementation can speed up the calculation. The above graph shows the benefit of setting intra-op threads correctly.

So, we should probably set some sensible defaults, but since different models that can exploit these settings in different ways, we should expose both. We could probably infer execution mode parallel if number of inter-op threads > 1, else sequential.

**Comment by bratseth** [comment]
Thanks for the explanation. Yes, then we need 2. I wish they didn't choose such bad names, but it's probably better to keep them.

**Comment by lesters** [comment]
The above PR merged code for adding the following options to services.xml:

```
<container version="1.0">
    ....
    <model-evaluation>
        <onnx>
            <models>
                <model name="reranker_margin_loss_v4">
                    <intraop-threads>4</intraop-threads>
                    <interop-threads>4</interop-threads>
                    <execution-mode>parallel</execution-mode>
                </model>
            </models>
        </onnx>
    </model-evaluation>
    ...
</container
```

Since stateless model evaluation is based on auto-discovery of models under the `models` directory in the application package, the above would only be needed for models that should not use the default settings. 

Current defaults are `execution-mode=sequential`, `interop-threads=1` and `intraop-threads=CPUs / 4`.
