### ISSUE TITLE
Index corruption with 'Cannot allocate memory' without hitting pod's requests.memory

### ISSUE THREAD

**Issue by nehajatav** [vespa-engine/vespa#23392]
In our vespa cluster with v7.559.12, we worked around [this issue](https://github.com/vespa-engine/vespa/issues/22415) wrt resource sensing by using a prorated memory percentage. However, without exceeding pod requests.memory of 64G with max reaching 58G, we still ran into the same issue of index corruption with 'Cannot allocate memory' seen in logs.

We understand that the particular issue#22415 is fixed in higher vespa version, however, our concern is even with improved resource sensing, is there still a possibility of index corruption with 'Cannot allocate memory'. What can be a possible cause of this issue when the pod didn't even reach its requests.memory limit?

**Comment by bratseth** [comment]
58 is 90% of 64. If you have 64Gb memory, you should set max to something like 48Gb to allow for variable memory allocations during index operations.

I don't see any evidence of actual index corruption, meaning the data on disk being corrupted here - those reads in the other issue failed just because of not enough memory.
