### ISSUE TITLE
Java client for Vespa

### ISSUE THREAD

**Issue by Mahdi-Seeker** [vespa-engine/vespa#24534]
**Is your feature request related to a problem? Please describe.**
I'd want to use Vespa in a Java application, but I can't find any java client for Vespa (except vespa-feed-client).

**Describe the solution you'd like**
I want to have a Java client for using Vespa, at least for searching... Of course it would be great if a full-featured java client (like Elasticsearch's java client) is available, but a search client would suffice for now.

**Describe alternatives you've considered**
It seems that the only alternative to using a Java client, is having to call REST APIs and manually converting the result to Java objects.

**Additional context**
None

**Comment by bratseth** [comment]
There is a Java client for writing documents: https://docs.vespa.ai/en/vespa-feed-client.html

There is also a standalone library for building queries: https://javadoc.io/doc/com.yahoo.vespa/client/latest/ai/vespa/client/dsl/package-summary.html
however, the most common, and efficient way to use Vespa is to just send HTTP requests containing your data as-is and then use [Searchers](https://docs.vespa.ai/en/searcher-development.html) inside Vespa to build the query from it programmatically, and then the need for a client is somewhat diminished because your request is just a simple http request.

**Comment by Mahdi-Seeker** [comment]
> There is a Java client for writing documents: https://docs.vespa.ai/en/vespa-feed-client.html

Yes I saw that, but it lacks some functionalities such as bulk indexing. How should I do that efficiently?

> There is also a standalone library for building queries: https://javadoc.io/doc/com.yahoo.vespa/client/latest/ai/vespa/client/dsl/package-summary.html

Thanks, I'll check it out!

> however, the most common, and efficient way to use Vespa is to just send HTTP requests containing your data as-is and then use [Searchers](https://docs.vespa.ai/en/searcher-development.html) inside Vespa to build the query from it programmatically, and then the need for a client is somewhat diminished because your request is just a simple http request.

I see. What HTTP client do you suggest for Java? I saw some VespaAsyncHttpClientBuilder & VespaHttpClientBuilder classes in http-utils maven package, are these the correct entry point for sending HTTP requests to Vespa?

And after all, thanks for your great work on Vespa!

**Comment by bratseth** [comment]
> Yes I saw that, but it lacks some functionalities such as bulk indexing. How should I do that efficiently?

You can do bulk indexing maximally efficiently with this client since it is based on HTTP2 streaming. Details in https://blog.vespa.ai/http2/

Or, if you mean on the receiving end, all writes to Vespa are applied one by one in real time and has been so for a long time. Special bulk operations aren't really more efficient when this is done right.

On HTTP clients, we don't want to recommend any since we haven't done any systematic evaluation. We have most experience with the Apache HTTP client. That surely works well but so does most others probably. See also this on HTTP best practices (for cloud, but most of it generally applicable): https://cloud.vespa.ai/en/http-best-practices

**Comment by Mahdi-Seeker** [comment]
> You can do bulk indexing maximally efficiently with this client since it is based on HTTP2 streaming. Details in https://blog.vespa.ai/http2/

Thanks!

One other question: do you recommend enabling compression on HTTP/2? I found nothing about it in the docs.

**Comment by bratseth** [comment]
Yes, you should generally use compression if the queries or writes are large.

**Comment by jobergum** [comment]
>Also compression is not supported in the vespa-feed-client.
That is correctly observed, and that is something we plan to address. Ideally, we want to be able to support zstd compression, see https://github.com/vespa-engine/vespa/issues/18644.

**Comment by kkraune** [comment]
Thanks for great questions! We have made a few updates to the documentation, this is useful - closing the ticket :-)
