### ISSUE TITLE
"Illegal instruction" when using newest docker image

### ISSUE THREAD

**Issue by neuhausler** [vespa-engine/vespa#25892]
**Describe the bug**
Running latest docker image fails with `Illegal instruction`

**To Reproduce**
docker run vespaengine/vespa:8
/usr/local/bin/start-container.sh: line 67:    10 Illegal instruction     /opt/vespa/bin/vespa-start-configserver

**Environment (please complete the following information):**
5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

**Vespa version**
Version 8:latest

**Additional Information**
Previous version for example vespaengine/vespa:8.108.22 works fine, and so does running latest version on MacOS.

**Comment by baldersheim** [comment]
That is most likely because we changed to compile for haswell architecture to get avx2.
That gives faster code, but might be too aggressive.

Which HW are you running on ?
What does 'cat /proc/cpuinfo' say ?

**Comment by neuhausler** [comment]
Good point .. we are running some older boxes/cpus in our datacenter, example:

Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz

.. still performant enough for our current vespa deployment :-)

**Comment by baldersheim** [comment]
To sum up a longer discussion we have had today:
We will flip back to make the rpms and docker images usable for all variants of the x86_64 instructions sets.

In the longer run we will probably release multiple variants optimized for different cpus, but with longer release cycles for older architectures due to the increasing cost of build/test/release pipelines.

The parts of the code that we know will benefit from utilizing certain instruction sets will do so by selecting implementation based on cpu architecture. However that does not scale for the whole c++ codebase we have. 

Normally the improvement from a newer cpu generation is not large enough to justify compiling for that instruction set. Most of the code runs fine on any variant of the basic instruction set. But from time to time the accumulated change of upping the bar makes it worthwhile. Also the compilers have become better at vectorizing and more eager at loop unrolling, all features favoring later instruction sets with more and larger registers.

And one early morning me and another accomplice decided that it was time to make the leap. Haswell had passed its 10 years anniversary and its predecessors should have long been laid to rest. The gain of changing from sandybridge to haswell ranged from 3-10% measured on icelake cpus. No one was running that old hw anymore....... However being proven utterly wrong, I humbly offer my apologies and accept the public humiliation and any consequences in this, and later lives.

The first release next week, which I guess will be 8.123.something, should again make the latest and greatest vespa version usable to you.

And again, sorry for the inconvenience, and thank you for your patience.
I will keep this issue open until the storm has passed, the ocean calm and the sun back on clear bright blue sky.

**Comment by neuhausler** [comment]
:-) thanks, will give the new version a try, and greetings to the great team at vespa.ai .. and a good reminder to overhaul our ancient hardware.

**Comment by aressem** [comment]
Fix released in `8.128.22`. Latest is now `8.131.17`.
