### ISSUE TITLE
Vespa visit operation should support writing output in multiple files

### ISSUE THREAD

**Issue by sunil924** [vespa-engine/vespa#26134]
**Is your feature request related to a problem? Please describe.**
In case of a full visit operation, vespa visit writes data as an big json array. 
In a big cluster, having a big single file is not a good idea. 
It is suggested that we can use the jq to covert the output in jsonl and then split it but it does not work successfully when data is huge. We have tried it with 41M doc cluster.

**Describe the solution you'd like**
vespa-visit-cli should take the output directory as input and no of documents or size of a file as batching criteria. visit operation should create multiple files based on the batching params.
The preferred format will be jsonl

**Describe alternatives you've considered**
jq with split

**Additional context**

**Comment by kkraune** [comment]
Thanks for submitting!

Yes, I agree using JSONL will make this much easier.

As a side note, we are working on providing examples of how to dump data to storage in https://github.com/vespa-engine/sample-apps/blob/master/examples/google-cloud/cloud-functions/go/visit.go 

As you can see, the code will support jsonl. We hope to get time to write the storage part soon, and for AWS as well. I think the file size should be configurable.

For your use case, will the code above fit your use case (i.e. are you running in Google Cloud or AWS), or are you running in a different environment where you can easily run vespa-visit? We are also working on supporting visit in https://docs.vespa.ai/en/vespa-cli.html, too.

I know this is a lot of info, bear with me, any input about your use case is help for us to provide the tools and examples :-)

----

side note: `jq --unbuffered` is preferred for large data downloads

**Comment by sunil924** [comment]
Thanks @kkraune for your response.
Yes, we tried with jq --unbuffered as well.

**Comment by jobergum** [comment]
I don't think we should invest more time in `vespa-visit`; we are moving to HTTP based APIs and the HTTP visit also supports slicing, which allows forking the visit over multiple clients. https://blog.vespa.ai/sliced-visiting/

**Comment by sunil924** [comment]
regarding visit.go -> It seems we are using HTTP apis. Http apis does not support downloading the deleted documents.
would the new Http visit will support emitting deleted documents in output?

Would there be a new tool using HTTP APIs?

Using Vespa CLI, can we run the process from outside the vespa cluster?

We are running vespa on in-premise Kubernetes cluster.

**Comment by jobergum** [comment]
If that is a must-have feature, that should then be available in the HTTP APIs. We are planning on adding visit support to `vespa-cli`, but it will just use the underlying HTTP API's.

**Comment by jobergum** [comment]
My point is that we should not invest any more time in the `vespa-visit` utility.

**Comment by vekterli** [comment]
https://github.com/vespa-engine/vespa/pull/26165 (present in version 8.130.29 and beyond) adds JSONL output support to `vespa-visit`, which should make it quite a bit easier to do streaming post-processing of the data it emits.

I think adding file writing support to `vespa-visit` would add a bit too many responsibilities to the tool. I see it predominantly as a generic stream source of document data; what happens with the data (business logic) is not its concern. Adding multi-file writing support sounds simple on the surface, but there are quite a few things that would have to be considered:

 * How to handle resumption of a previously aborted/crashed visit (last output file may be truncated)
 * Domain-specific naming conventions for the archive files
 * Compression of document streams. How to handle truncated (corrupt) compression from a previously crashed visit.
 * Remote storage support since the combined document data in a cluster is usually way too large to fit on a single node.
 * etc.

I definitely see the use case for e.g. chunked archiving, but I think it would be best off as a separate tool (possibly even entirely unrelated to Vespa, assuming it works generically on JSONL streams).
