### ISSUE TITLE
Vespa cluster unable to recognize last deployed application after cluster deletion and creation

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#26724]
**Describe the bug**
We are currently using podman for running our vespa application. We are mounting the paths /opt/vespa/var and /opt/vespa/logs to our host local disk. We observed that upon deletion of the cluster and then bringing them up the application generation is not restored to the latest

Upon checking the application generation it seems like the generation shows 0 
 curl -s http://localhost:19071/state/v1/config
{
  "config" : {
    "generation" : 0,
    "container" : {
      "generation" : 0
    }
  }
}

**To Reproduce**
1. Destroy entire cluster
2. Bring up the entire cluster
3. Perform health check for container and content nodes

**Expected behavior**
vespa should be able to recognize the latest deployed application of the var path is persisted after destroying the clsuter.

**Environment (please complete the following information):**
 - OS: RHEL8
 - Infrastructure: Podman
 - Versions vespa - 8.137.25

**Vespa version**
8.137.25

**Additional context**

**Comment by kkraune** [comment]
I am not sure what you mean by "Destroy entire cluster".

It seems to me that you want to replace container and content nodes, but keep the config server nodes. So http://localhost:19071/state/v1/config is unchanged during the procedure, as nothing is done on the config server nodes.

I.e., using https://github.com/vespa-engine/sample-apps/tree/master/examples/operations/multinode-HA as an example, nodes 0,1,2 are config server nodes are unchanged, and nodes 3-9 are replaced.

**Comment by 107dipan** [comment]
Hey Kristian, 
By destroying the cluster I meant if we delete all node nodes together and then bring it up.

**Comment by kkraune** [comment]
please confirm that you did not delete the config server nodes - and how do you delete nodes?

**Comment by 107dipan** [comment]
We deleted the podman containers. Podman rm -f pod-name

**Comment by kkraune** [comment]
I see - so the problem is how to replace a config server podman container instance, keeping the deployed application config.

Note that http://localhost:19071/state/v1/config is expected to be 0 after a fresh config server start, as this is the config server's config generation, not the deployed application.

A better test is to (using multinode-HA as an example):
* have the 3+7 nodes running
* stop all 3 config servers (delete the podman containers) - the cluster shall still work, serving queries
* try to restart one of the vespa container instances (this should fail as there are no config servers running - Vespa will not start on that node)
* start the config servers - use https://docs.vespa.ai/en/operations/configuration-server.html to ensure they start properly
* try to restart one of the vespa container instances - this time, it should start

**Comment by 107dipan** [comment]
I have one query regarding the above mentioned steps. Do we need to deploy the application after starting the configservers.

**Comment by kkraune** [comment]
It is not needed to deploy the application again after starting the config server, correct me if I'm wrong, @hmusum

**Comment by hmusum** [comment]
That is correct @kkraune

**Comment by 107dipan** [comment]
Thanks for the suggestion, Let me try this out with our current setup and get back to you on this.
