### ISSUE TITLE
Queries regarding parent child schema in vespa 

### ISSUE THREAD

**Issue by 107dipan** [vespa-engine/vespa#27805]
Hi Vespa Team, 

I was looking into parent/child schemas and wanted to clarify a few things for my understanding. We are looking at defining a parent schema and inheriting the same in the different document types we have defined. 
We were looking into this for reference https://docs.vespa.ai/en/parent-child.html

1. A document type only becomes global only when explicitly defined. A doc type defined as a parent schema doesnt become a global schema.
2. When document with a child doc type is indexed, the indexing is only done to the nodes on which it gets replicated and not all the content nodes. 

Is there any considerations to be made while defining a parent-child schema that can affect our performance negatively.

**Comment by bratseth** [comment]
It's important to not confuse the parent-child feature and schema (or document type) inheritance.
- The **parent-child feature** allows you to have run-time references between instances of two different document types, where the documents being referred to (the parent) must be global, such that they are available locally on the content node during evaluation.
- **Inheriting between schemas** (or document types) is a config-time feature which allows you to include configuration constructs (such as fields and rank profiles) from a common schema rather than duplicating them in each inheriting schema.

**Comment by 107dipan** [comment]
Thanks a lot for the clarification!
