### ISSUE TITLE
App bundles compiled with newer versions of JDK fail to run

### ISSUE THREAD

**Issue by eric-millin** [vespa-engine/vespa#27837]
**Describe the bug**
I want to use features in my app bundle that are only available in JDK 19+. When I try to deploy the bundle, I see the following error in the logs:

> ERROR   container        Container.com.yahoo.jdisc.core.StandaloneMain        JDisc exiting: Throwable caught: \nexception=\njava.lang.UnsupportedClassVersionError: com/some/thing has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0\

Also note that the API response indicated that the bundle was `prepared and activated`.

**To Reproduce**

1. Build a bundle compiled with JDK 19
2. Deploy it
3. Watch it fail

**Expected behavior**
I can use at least current JDK version - 1 to build my bundle.

**Environment (please complete the following information):**
 - Docker container: `vespaengine/vespa:8.194.16`

**Vespa version**
8.194.16

**Comment by gjoranv** [comment]
Hi Eric,

Thanks for raising the GitHub issue.

Vespa currently supports only the latest LTS release of the JDK. Thus, deploying an app bundle built with JDK 19+ won't work due to compatibility constraints. We're planning to upgrade Vespa's runtime to JDK 21 by the end of 2023 to accommodate newer features.

Until then, please use JDK 17 for seamless deployment.

Feel free to reopen this issue if your have any more questions.

Regards,
Gjøran
