### ISSUE TITLE
vespa-cli deploy should handle configuration server yet not started gracefully

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/vespa#27884]
```
$ docker run --detach --name test --hostname vespa-container \
  --publish 8080:8080 --publish 19071:19071 \
  vespaengine/vespa

$ vespa deploy
```

It can often end with the following:

```
Uploading application package ... failed
Error: Post "http://127.0.0.1:19071/application/v2/tenant/default/prepareandactivate": write tcp 127.0.0.1:65315->127.0.0.1:19071: write: broken pipe
```

It would be nice if the deploy upload could handle this gracefully and retry for some time. 

This would simplify guides and easier to write one-liners, avoiding having to wait for status as a separate command. 

<img width="614" alt="image" src="https://github.com/vespa-engine/vespa/assets/20928528/afc1d3ba-476e-4f42-bc31-0d04bd037922">

**Comment by mpolden** [comment]
Agree, but we need to redesign how waiting and service discovery works in general (some related discussion in #27208). Expectations of `--wait` vary between commands. These are some of the things we can wait for:
1. Wait for configserver up (self-hosted) or wait for controller up (cloud)
2. Wait for config convergence (self-hosted) or deployment to complete (cloud)
3. Discover endpoints (currently cloud only, but we want this for self-hosted too)
4. Wait for service `X` up (self-hosted and cloud). `X` is detected by default if there is only one cluster, otherwise the user must specify `--cluster` (cloud only due to lack of discovery for self-hosted).
5. Wait for all services up  (self-hosted and cloud)

Today `--wait` always means 2+3+4.

I guess we want `deploy --wait` to be 1+2+3+5, `status deploy --wait` should only be 1, while `query --wait` should be 4 and/or 5.
