### ISSUE TITLE
 Support default value for the `path` type configuration parameter

### ISSUE THREAD

**Issue by dainiusjocas** [vespa-engine/vespa#27912]
**Is your feature request related to a problem? Please describe.**
I'm building a custom Vespa component that might need some configuration. The configuration is specified [here](https://github.com/dainiusjocas/journal/blob/main/src/journal/vespa/linguistics/lucene/src/main/resources/configdefinitions/lucene-analysis.def). Configuration in my case is a `Map<String, String>` where some values are relative paths to some file. The `configDir` parameter of type `path` works perfectly. However, in cases when my component doesn't refer to any files, requiring a param seems a bit too much.

**Describe the solution you'd like**
`path` type configuration parameters support a default value specified in the `.def` file.

**Describe alternatives you've considered**
Do nothing.

**Additional context**
- Component source [code][(https://github.com/dainiusjocas/journal/tree/main/src/journal/vespa/linguistics/lucene](https://github.com/vespa-engine/vespa/blob/master/lucene-linguistics/src/main/resources/configdefinitions/lucene-analysis.def#L7))
- The Slack [thread](https://vespatalk.slack.com/archives/C01QNBPPNT1/p1690449707163629).

**Comment by hmusum** [comment]
We have had a look at this and supporting a default value is not straightforward. The value supplied will be changed by the config system to point to a file on the node, eg. `files/my-file.txt` will be transformed so that the client will see `/opt/vespa/.../aed13fc6a/my-file.txt` and the client will use that path to read the file. File distribution will transfer the file to container nodes. Using some magic default value will still require a valid path on the client side and the need for some hacks in the file distribution code, so we probably want to have a new config type to support this instead. Which will require some work

**Comment by dainiusjocas** [comment]
Thanks for an update! To sum up:
- `path` type config requires a value(?)
- files or directories specified with the `path` parameter are properly distributed to all container nodes
- In the future there might be another configuration parameter type that would help with the file distribution(?)

**Comment by hmusum** [comment]
Yes, that's right on all accounts

**Comment by hmusum** [comment]
Support for `optional` keyword for a config field of type `path` has been implemented. Documented at https://docs.vespa.ai/en/reference/config-files.html#path when https://github.com/vespa-engine/documentation/pull/2884 has been merged.

Basically you can define a field in the config definition file as

`configDir path optional`

and specify `configDir` in services.xml when it has a value (otherwise it will be empty).


In Java code you now need to use an Optional for the config value:

`Optional<Path> configDir = config.configDir();`


Released in Vespa 8.224.19. Please let me know if this does not work out for you or you have any questions.

**Comment by dainiusjocas** [comment]
> Support for `optional` keyword for a config field of type `path` has been implemented. Documented at https://docs.vespa.ai/en/reference/config-files.html#path when https://github.com/vespa-engine/documentation/pull/2884 has been merged.
> 
> 
> 
> Basically you can define a field in the config definition file as
> 
> 
> 
> `configDir path optional`
> 
> 
> 
> and specify `configDir` in services.xml when it has a value (otherwise it will be empty).
> 
> 
> 
> 
> 
> In Java code you now need to use an Optional for the config value:
> 
> 
> 
> `Optional<Path> configDir = config.configDir();`
> 
> 
> 
> 
> 
> Released in Vespa 8.224.19. Please let me know if this does not work out for you or you have any questions.

Awesome, thank you! Soon I'll try out how this helps simplifying the  Lucene Linguistics component configuration.

**Comment by dainiusjocas** [comment]
> Support for `optional` keyword for a config field of type `path` has been implemented. Documented at https://docs.vespa.ai/en/reference/config-files.html#path when https://github.com/vespa-engine/documentation/pull/2884 has been merged.
> 
> 
> 
> Basically you can define a field in the config definition file as
> 
> 
> 
> `configDir path optional`
> 
> 
> 
> and specify `configDir` in services.xml when it has a value (otherwise it will be empty).
> 
> 
> 
> 
> 
> In Java code you now need to use an Optional for the config value:
> 
> 
> 
> `Optional<Path> configDir = config.configDir();`
> 
> 
> 
> 
> 
> Released in Vespa 8.224.19. Please let me know if this does not work out for you or you have any questions.

Awesome, thank you! Soon I'll try out how this helps simplifying the  Lucene Linguistics component configuration.
