### ISSUE TITLE
component url model is downloaded each time services.xml is deployed

### ISSUE THREAD

**Issue by eostis** [vespa-engine/vespa#28012]
Here a capture of the Vespa's logs after a redeployment of services.xml.

The lack of caching could be due to the redirection of the Dropbox url?

![image](https://github.com/vespa-engine/vespa/assets/1785759/94e48c4b-a6f2-4a8e-8367-54dfb5521de1)

**Comment by jobergum** [comment]
A URL file is expected to be downloaded if the deployed configuration caused a change so components need to be re-created. There is no caching mechanism.

**Comment by eostis** [comment]
I notice that other urls are cached:
<img width="1328" alt="image" src="https://github.com/vespa-engine/vespa/assets/1785759/79e0f890-22e7-4646-a307-8c16cfedb42b">

I thought it was the norm to cache urls.

**Comment by hmusum** [comment]
The HTTP request adds the `If-Modified-Since` header when downloading. If the server does not honor this (as [this Dropbox forum post](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/If-Modified-Since-and-Last-Modifed-headers/td-p/217613) suggests, it will be downloaded every time. This would also explains why you are seeing this for only some URLs.

That said, the plan is to change this to never download an url if we already have cached it. Which means that you need to use a new/changed url if new content is wanted.

**Comment by eostis** [comment]
> That said, the plan is to change this to never download an url if we already have cached it

Does that mean the cloud storage urls like Dropbox will be cached then?

Currently, each redeploy takes minutes and downloads GBs. And cloud storage urls are the only scalable solution.

**Comment by hmusum** [comment]
Yes, that's the plan, but I haven't looked at the details and I have no ETA for this yet.

**Comment by eostis** [comment]
Thanks.

**Comment by hmusum** [comment]
Cached URLs will always be used if already download, available in Vespa 8.217.31

**Comment by eostis** [comment]
@hmusum Works great with 8.217.46: the Dropbox model is cached as expected.
