### ISSUE TITLE
Vespa not protecting content nodes from overload.

### ISSUE THREAD

**Issue by buinauskas** [vespa-engine/vespa#28579]
**Describe the bug**

Vespa queues search queries indefinitely and keeps on executing them in the content nodes even when the load has stopped.

**To Reproduce**
1. Use a single content node vespa cluster
2. Use 100 unique sampled search queries from organic traffic
3. Use https://locust.io as a loading test tool to stress test vespa at ~10K QPS with the queries from step 1
4. All vespa queries time out with HTTP status code 504
5. After stopping the load test, vespa still time out with HTTP status 504
6. By looking at container/content node metrics, it is obvious that the content node keeps executing queued queries in the background, which is visible from the match task queue.
7. Once the queue is drained, the cluster comes back to normal. Alternatively, one can restart the content node to wipe the queue.

**Expected behavior**

An overloaded system should respond with HTTP status code 429 (too many requests) and prevent itself from being taken down.

**Screenshots**

<img width="2538" alt="image" src="https://github.com/vespa-engine/vespa/assets/7301441/42ed493f-32a1-4c44-87e0-c3829d091472">
<img width="2538" alt="image" src="https://github.com/vespa-engine/vespa/assets/7301441/f3182dfd-7ee0-4de7-b123-8eaf29bfb524">

**Environment (please complete the following information):**
 - OS: Rocky Linux
 - Infrastructure: self-hosted
 - Versions 8.8
 - Vespa deployment: Dockerized

**Vespa version**
8.213.13

**Additional context**

- vespa-proton-bin CPU profiles during the load test and after the load test: https://gist.github.com/buinauskas/276b8302f10697c03c713216b53671c6

**Comment by baldersheim** [comment]
Thanks for the detailed information. This is indeed suboptimal overload handling.
Correct behavior would be to observe reduced coverage during overload period, and 100% coverage once load is within limits again. This is documented in https://docs.vespa.ai/en/graceful-degradation.html

However this not perfect. If more time is spent during query setup phase in the backend, than is allowed in the request controlled by the **timeout** parameter, graceful degradation is not applied. The reason for this is that we have assumed that matching and ranking phase of a query is the most expensive one. Most of the time that is correct. However as more cores are added to the cpus this is becoming less and less so. Matching and ranking is done multithreaded, while query setup is still single threaded. Hence the setup phase takes relatively longer time compared to matching and ranking measured in wall clock time.

There are also some parts of the query features that under given circumstances precompute intermediate posting lists during query setup. One of them are range search., and that is confirmed by looking at the performance profile here.
When setting up range search there are some heuristics applied, that get it right most of the time, but sometimes takes too long to do the wrong thing.

In order to improve this scenario it would be good to get more information.
1 - The response when running the query with these query parameters added "&hits=1&timeout=10&tracelevel=1&explainlevel=2&trace.timestamps".
2 - Run the query without the range terms with the same parameters as above.

3 - We have improved adherence to the timeout so that the massive backlog should not happen anymore. That was done in https://github.com/vespa-engine/vespa/pull/28575. That is part of 8.230.15 and on. If all is well 8.230.16 will be available within the next 24 hours.

**Comment by jobergum** [comment]
Hey @buinauskas, could you upgrade to the latest and verify that you don't see long-running queries? Also, to improve the overall performance of your queries, the information requested above would be great.

**Comment by baldersheim** [comment]
@buinauskas has confirmed that overload handling is now working as expected.
