### ISSUE TITLE
Pyvespa deployment fails

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/vespa#30219]
Reported by @Gladiator566 in https://github.com/vespa-engine/pyvespa/issues/663 - error message is

"Value of X-Content-Hash header does not match computed content hash"

This can happen when deploying to Vespa Cloud - see some of the comments in https://github.com/vespa-engine/pyvespa/issues/663 for more details

**Comment by jobergum** [comment]
There is a time component in the hash that might explain this

**Comment by tmaregge** [comment]
It appears the issue might be caused by the uppercase letter "M" present in the application name used by @Gladiator566. When I used the application name "bgeM3", as mentioned in this [comment](https://github.com/vespa-engine/pyvespa/issues/663#issuecomment-1929103326), I also got a content hash mismatch. Changing the name to "bgem3" fixed the issue.

I'm not sure if this is a Pyvespa-specific error or if Vespa simply doesn't support application names containing capital letters. Will investigate further.

**Comment by tmaregge** [comment]
Update: Vespa doesn't support uppercase letters in application names. Will add a more appropriate error.

**Comment by Gladiator566** [comment]
thanks a lot, lowercase letter like "bgem3" works well

**Comment by kkraune** [comment]
Thanks @tmaregge ! Closing this then, will release pyvespa shortly
