### ISSUE TITLE
The bm25 is 0 when the query and documents is chinese

### ISSUE THREAD

**Issue by LoveFishoO** [vespa-engine/vespa#30639]
**Describe the bug**
The bm25 is 0 when the query and documents is chinese. Maybe I think the bm25() function is not support to chinese. 

my embedding model is bge-m3. Therefore, i also store the sparse vectors in the vespa.

How do i use  vespa enigne to calculate the bm25 when my query and documents are both in chinese?

**Comment by jobergum** [comment]
Hey! 

[BM25](https://docs.vespa.ai/en/reference/bm25.html)  is a scoring function working on tokens produced by Language specific tokenizers. See [linguistics](https://docs.vespa.ai/en/linguistics.html). The default linguistic integration in Vespa doesn't support CJK languages out of the box which can explain why you see BM25 scores of 0. 

Alternatives

- Use [Lucene linguistics](https://docs.vespa.ai/en/lucene-linguistics.html) instead of Apache OpenNLP 
- Use [Jieba](https://github.com/vespa-engine/sample-apps/tree/master/examples/vespa-chinese-linguistics)

**Comment by jobergum** [comment]
I'm resolving this, feel free to re-open if you struggle with using mentioned CJK linguistic options. Thank you!
