### ISSUE TITLE
What's the difference between Tensor and Vector within other vector databases? 

### ISSUE THREAD

**Issue by misslorac** [vespa-engine/vespa#30794]
Regarding to the model inference of document reranking, vespa directly adopts external tools such as onnxruntime for model serving, as a result, what's the aim of providing such data types?

I notice that there are some operations dedicated for tensors within vespa, however, what are the scenarios of using tensors? It seems vector or embedding is enough: for vector search, just use vector index; for model inference, just use external libraries.

**Comment by bratseth** [comment]
There are lots of scenarios where you want to store or pass some data which has more than one dimension, and compute over it directly to achieve some functionality, especially since Vespa tensor dimensions can also be sparse, and therefore be used to represent maps of numbers, maps of vectors etc., see for example https://blog.vespa.ai/announcing-long-context-colbert-in-vespa/ which uses tensor computations to achieve SOTA relevance.

Furthermore, the latter can also be indexed which makes it possible to use vector search to recall chunks within documents rather than just standalone chunks, see https://blog.vespa.ai/semantic-search-with-multi-vector-indexing/
