### ISSUE TITLE
What's the status of vespa engine?

### ISSUE THREAD

**Issue by yingfeng** [vespa-engine/vespa#3213]
Is it production ready? I could see frequent daily updates from commit histories, what's the roadmap as a result ?

**Comment by bratseth** [comment]
Yes, it is production ready.
We upgrade our own production systems with the latest version about a couple of times a week.
The latest release verified as production ready at the time of writing is 6.141.35 (https://github.com/vespa-engine/vespa/releases/tag/6.141.35)

We publish binaries for those versions, which you can access as described in the getting started section under http://docs.vespa.ai

We haven't started to publish jars yet, so if you want to add your own application code you'll need to build the Java parts of the platform yourself first. Sorry about that, it will be fixed in a few days.

**Comment by bratseth** [comment]
Roadmap: I don't have one with dates available at this time, but see https://github.com/vespa-engine/vespa/blob/master/TODO.md

**Comment by yingfeng** [comment]
Do you have a roadmap document such that I could catch up the frequent commits ?  Thank  you~

**Comment by yingfeng** [comment]
Thanks a lot~
