### ISSUE TITLE
Windows Enviroment

### ISSUE THREAD

**Issue by rodrigoporcionato** [vespa-engine/vespa#3638]
Hi,

Is possible to configure the Vespa Engine in Windows? If yes, how? Can introduce some tutorials?

**Comment by jobergum** [comment]
Hi @rodrigoporcionato, 

Thank you for your interest in Vespa!

Using vespa docker image on a Windows node is doable but we faced a few challenges with making the our quick start guide work with docker on windows but it's something we would like to address soon so that developers on windows can use vespa through docker on their laptops.

**Comment by bratseth** [comment]
I guess you can make it work with some tweaking @rodrigoporcionato. If you do, please submit a PR with a windows quick start, or the steps needed to create one.

**Comment by aressem** [comment]
Windows quick start is here:
http://docs.vespa.ai/documentation/vespa-quick-start-windows.html
