### ISSUE TITLE
does vespa with multiple search containers provide service-discovery for front-end applications?

### ISSUE THREAD

**Issue by knowmara** [vespa-engine/vespa#4671]
looking forward to your answers,thanks.

**Comment by bratseth** [comment]
A search container is an instance of a container running the search middleware, i.e configured with 
```
<container> 
    <search> 
```
in services.xml.

Whether you have one or multiple container instances (or clusters), and whether or not they run the search middleware, they have a built-in root handler by default which exposes all the handlers and their bindings, which can be used for discovery (by frontend developers).

But maybe you are asking about something else?

**Comment by knowmara** [comment]
Thanks for your answer.
Sorry for my confusing question,what I actually want to say is that how front-end applications can get the host:port pairs of all the container instances while we have multiple nodes for search container..
it like this,
<container>
      <search>
      </search>
      <nodes>
              <node1 ...>
              <node2....>
              <node3....>
              .....
      </nodes> 
</container>
 thanks.

**Comment by bratseth** [comment]
There is no API that exposes this by default. You could make one by creating a simple RequestHandler which takes an instance of com.yahoo.cloud.config.ClusterInfoConfig, as that config contains the info you need.

However, to me it seems about equally hard to know one container host as to know all of them, so I would rather do this by asking a config server what the hosts are. The config server already has an API which returns every config. I think the URL you need is

http://[your-config-server-host]:4080/config/v2/tenant/default/application/default/environment/default/region/default/instance/default/cloud.config.cluster-info/[your-container-cluster-id]

The other common way to do this is to set up a VIP between the frontend and containers.

**Comment by knowmara** [comment]
Thanks.
According to my understanding,either way is static, and if  front-end applications want to be notified immediately when the container list changes,i.e some nodes down, we either pool the URL or manually modify the VIP. I understand correctly？

**Comment by jobergum** [comment]
For container nodes being 'down' and VIP handling please see http://docs.vespa.ai/documentation/jdisc/vip.html

**Comment by knowmara** [comment]
All right,thanks.

**Comment by bratseth** [comment]
Note that if you don't want to use a VIP you can do the same from a library in your frontends:
Get the configured set of container nodes.
Monitor them (from the client) by requesting status.html from each container periodically and take any who don't respond 200 OK out of rotation.

**Comment by knowmara** [comment]
Appreciate your answer.
The problem with this approach is that when the node increases, there is no way we can dynamically notify the frontend because the adding node is manually configured in service.xml unless we manually change the frontend program's setting about the container nodes. In fact, there are another question i would like to discuss, why not remove the node information from the service.xml, let vespa help us to schedule it, only need to increase vespa scheduling function on it.

**Comment by bratseth** [comment]
There are two separate things to keep track of here: The *configured* list of nodes in a cluster, and the *currently live* nodes in a cluster.

The configured nodes is part of the configuration of the system, whether it is set in services.xml or through some other mechanism (more on that below). Your frontends (or VIP) must get to know about the configured set of nodes to talk to somehow - either by reading the same configuration (e.g services.xml), by polling some API inside Vespa (the config API described earlier, one you provide, or the option described below), or by a push notification mechanism (I do not recommend that option because it leads to the additional problem of making sure all frontends are actually notified, even when some are down, the set of frontends change etc.).

The currently live nodes is the subset of configured nodes which are actually responsible from the point of view of the frontend (or VIP). Regardless of config mechanism, this must be maintained by live by the frontend through health checking as described above.

Regarding configuring nodes in services.xml (and hosts.xml). There is actually another mechanism built into Vespa. When the config model inside Vespa is built (from the application package), it delegates node allocation to an instance of the Provisioner API: https://github.com/vespa-engine/vespa/blob/master/config-provisioning/src/main/java/com/yahoo/config/provision/Provisioner.java
The default implementation of this returns nodes by reading info from services.xml and hosts.xml. However, you could plug in an implementation which allocates nodes in some other way, such that you can write <nodes count="5" flavor="some-node-flavor"/> in services.xml instead of providing a list of nodes. There is already an implementation of this in Vespa which uses ZooKeeper to persist node allocations - see https://github.com/vespa-engine/vespa/tree/master/node-repository.
This is useful for large installations which many applications with dynamic node allocations. However, setting it up for just one or a few applications is not worth the effort, and we don't provide user level documentation for it at the moment.

**Comment by knowmara** [comment]
Thank you very much for the detailed solution.
