### ISSUE TITLE
REST Document Api crash

### ISSUE THREAD

**Issue by Flakesz** [vespa-engine/vespa#5142]
Hey guys,

Tried to feed documents into vespa (30/s~) over the REST Document Api and was soon greeted by:

> {"errors":[{"description":"TOO_MANY_PARALLEL_REQUESTS Too many parallel requests, consider using http-vespa-java-client. Please try again later.","id":-8}]}

I get that it was too much for the REST Api and will switch to the java client but first I would like to get vespa up and running again.

ApplicationStatus & Health still looked fine afterwards but I fail to resolve the error. Connected to the container and restarted all services with the cli tools, also restarted the container itself, tried a redeploy of the app. but the error remains.

It seems like no worker threads were available at the time given the error respone. (taken from https://github.com/vespa-engine/vespa/blob/master/vespaclient-container-plugin/src/main/java/com/yahoo/document/restapi/resource/RestApi.java)

Does that mean the data is corrupted? If no, how can I fix it?

**Comment by bratseth** [comment]
No data is corrupted. If you restart the container then this condition will be gone, that is absolutely certain. If you don't restart then it will quickly self-correct.

If you don't observe this I guess it is because you keep applying more load than this interface can handle while restarting etc.

If you want to feed with high throughput, use the standalone Java client (from Java or the command line): http://docs.vespa.ai/documentation/vespa-http-client.html

(If you need to feed from many clients (each with a low load, typically from frontend nodes), then you could also increase the number of worker threads allocated for this, and of course you can always increase the capacity you can handle by adding more nodes, but 30writes/sec is very low.)

Sorry for the late answer.

**Comment by Flakesz** [comment]
Hey Jon, 

thanks for taking the time. The thing is that I isolated the node afterwards and stopped all incoming traffic to it. Restarted the container also a few times in the mean time.

As of now the condition is still there even over restarts without any load at all.

**Comment by bratseth** [comment]
This is just a Java process which doesn't write any state to disk, so it is literally impossible for it to retain this state.

You can see whether there is any traffic to the container by checking the access log under $VESPA_HOME/logs/vespa/qrs/
And you can see whether the container has started or not by issuing the command vespa-logfmt.
Details in http://docs.vespa.ai/documentation/reference/logs.html

One of those should tell you what is going on here. Since you mention 30 writes/sec I think you have some resource problem, because that is a very low number. Are you running this in Docker? How much memory do you allocate to each vm? The default is 2Gb, which will be too small if you run all the Vespa processes on it - it will work but be extremely slow.

**Comment by harryjackson** [comment]
I've been having a similar issue. If I start the container it won't allow me to start adding documents for some time. I get Connection refused error messages. If I wait for some time it starts accepting documents. 30 per/sec is very slow. It should be 1000's per/sec, on my laptop is getting up to 13000 per second.

https://github.com/vespa-engine/vespa/issues/5202

**Comment by bratseth** [comment]
>  If I start the container it won't allow me to start adding documents for some time.

Probably due to initialization of the content layer. If you shut it down without flushing it will replay the transaction log before becoming up. You can restart faster by flushing before shutdown - see http://docs.vespa.ai/documentation/reference/services-content.html#flush-on-shutdown

And you can find information about what Vespa is doing and when various interfaces are set up by issuing vespa-logfmt.
