### ISSUE TITLE
Failed to set up a config server cluster

### ISSUE THREAD

**Issue by knowmara** [vespa-engine/vespa#5419]
hi all,
according to the document of vespa,i set VESPA_CONFIGSERVERS,VESPA_CONFIGSERVER_ZOOKEEPER_QUORUM_PORT,VESPA_CONFIGSERVER_ZOOKEEPER_ELECTION_PORT in $VESPA_HOME/conf/vespa/default-env.txt on all nodes,but there seems a failure to setting up a Multi-node config servers.
Have I miss any configuration? and what is the correct way？
Thanks

**Comment by bratseth** [comment]
It's enough to set VESPAS_CONFIGSERVERS unless you have conflicts with ports used for something else. How does it fail?

**Comment by knowmara** [comment]
Sorry for the time difference, I'm sorry
After I configure VESPAS_CONFIGSERVERS, I will be prompted to **No value found for 'services.addr_configserver' or 'vespa_base.addr_configserver'** when I start the config server cluster, although the last show config server starts. Then when I use "**lsof**" to see listenning ports of the config server process, I can only see 19070, 19071 and 2181, and can not find the election port and communication port of zk. Do not I need to set the myid file for zookeeper? 
There is also a question, what is the role of configservers configuration options in service.xml.In my opinion,before the service.xml takes effect, configserver has been determined.

**Comment by bratseth** [comment]
**ZooKeeper ports:**
I'm sorry, the documentation on setting ZooKeeper ports is wrong. The right names for those are cloudconfig_server__zookeeper_electionPort and cloudconfig_server__zookeeper_quoromPort. 
I'll have the doc updated. However, how did you even get into this? :-) You don't need to set these.

**Do not I need to set the myid file for zookeeper?**

No.

**What is the role of configservers configuration options in service.xml**

It is a place to add non-bootstrap configuration on configservers. You are right that strictly the listing of the configserver hosts in there is redundant as it has to be the same as the bootstrap environment setting.

**Setting up a multinode system:**

I'm not sure if you have a working system or not? Just to be sure, here's how to make a multinode system work:
1. Your /opt/vespa/conf/vespa/default-env.txt should contain
override VESPA_CONFIGSERVERS full-hostname1,full-hostname2,full-hostname-3
You don't need to put anything else there (unless you want to change ports of config services for some reason).
2. Your services.xml and hosts.xml must configure those same hosts as configservers.
3. You need to run vespa-start-configserver on all the designated config servers and vespa-start-services on all the other nodes.
4. At this point you have a system running which does nothing and you can run vespa-deploy prepare [app-package] && vespa-deploy activate on any of the config servers to run an application.
5. vespa-logfmt -l warning,error (on an admin server) should show no problems, and vespa-logfmt should show that various services starts listening on various ports.

If you don't see this, please update the ticket with exactly what you see when doing which step.

**Comment by bratseth** [comment]
To @FrankYu0502: You guys are probing deep ...  :-)

If the ZK services on 2 and 3 is unreachable you should see that in the log: vespa-logfmt -l warning,error - do you?

Are you sure you looked at the right session?

You need to check the session which is the active one - that session number is the sole content in a file somewhere below /config/v2/tenants/default/ - I don't remember the exact name.

Note that not all files in the application package are distributed in ZooKeeper - only a whitelisted set. (ZooKeeper is not suitable for large files).

Let me know if any of this information helps.

**Comment by knowmara** [comment]
Thanks.
As far as I know, a zk cluster needs to have election ports and communication ports, which means that when the config server cluster starts successfully, I should see that the config server will listen on both ports. I configured it according to the steps mentioned above, but I don't seem to be able to see that the two ports are being monitored. In my opinion,It is irrelevant whether the config server cluster is successful and has no application deployed. Before deploying the application, config servers It should have been a cluster, I understand right?

**Comment by bratseth** [comment]
The defaults for those ZK ports are 2182 and 2183.
I don't remember exactly when and how they are listened to. Do you have a problem with this, or are you curious? If it's just the latter I think you need to look at the ZK source.

**Comment by FrankYu0502** [comment]
@bratseth Here is the warning I got after deploy prepare & activate 

[2018-03-26 20:58:27.585] WARNING : configserver     stderr	SLF4J: The following loggers will not work because they were created
[2018-03-26 20:58:27.585] WARNING : configserver     stderr	SLF4J: during the default configuration phase of the underlying logging system.
[2018-03-26 20:58:27.585] WARNING : configserver     stderr	SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
[2018-03-26 20:58:27.585] WARNING : configserver     stderr	SLF4J: org.apache.zookeeper.server.quorum.QuorumPeerMain
[2018-03-26 21:01:29.223] WARNING : configproxy      configproxy.com.yahoo.config.subscription.impl.JRTConfigRequester	Request callback failed: APPLICATION_NOT_LOADED. Connection spec: tcp/tj-s-staging-rec09.kscn:19070, error message: Failed request (No application exists) from Connection { Socket[addr=/10.38.10.6,port=25018,localport=19070] }
[2018-03-26 21:01:44.992] WARNING : configproxy      configproxy.com.yahoo.vespa.config.proxy.DelayedResponseHandler	Timed out (timeout 15000) getting config name=sentinel,namespace=cloud.config,configId=hosts/tj-s-staging-rec09.kscn, will retry
[2018-03-26 21:06:40.188] WARNING : config-sentinel  config-sentinel.config.frt.frtconnection	Connection to tcp/localhost:19090 failed or timed out
[2018-03-26 21:06:40.188] WARNING : config-sentinel  config-sentinel.config.frt.frtconnection	FRT Connection tcp/localhost:19090 suspended until 2018-03-26 13:07:20 GMT
[2018-03-26 21:07:01.834] WARNING : configproxy      configproxy.com.yahoo.config.subscription.impl.JRTConfigRequester	Request callback failed: APPLICATION_NOT_LOADED. Connection spec: tcp/tj-s-staging-rec11.kscn:19070, error message: Failed request (No application exists) from Connection { Socket[addr=/10.38.10.6,port=26189,localport=19070] }
[2018-03-26 21:07:02.992] WARNING : configproxy      configproxy.com.yahoo.vespa.config.proxy.DelayedResponseHandler	Timed out (timeout 25000) getting config name=sentinel,namespace=cloud.config,configId=hosts/tj-s-staging-rec09.kscn, will retry

**Comment by FrankYu0502** [comment]
@bratseth In host2 and host3, there is even no sessionId (ls /config/v2/tenants/default/sessions is empty).
However, in host1, there has everything (there are hosts.xml, searchdefinitions, services.xml, deployment.xml under /config/v2/tenants/default/sessions/2/userapp/)

**Comment by knowmara** [comment]
OK,thanks.

**Comment by FrankYu0502** [comment]
@bratseth 
Vespa running with a single configserver works perfectly. However, in order to ensure HA, I set up 3 configserver(host1, host2, host3) in default-env.txt, services.xml and hosts.xml configure same as configservers and start-configserver, start-services, deploy prepare & activate a sample application. It works well at this time. Then I just vespa-stop-configserver in host1. I get following log on all hosts:

1522120222.160	tj-s-staging-rec09.kscn	43121/32	configproxy	configproxy.com.yahoo.config.subscription.impl.JRTConfigRequester	info	Failure of config subscription, clients will keep existing config until resolved: name=jdisc-bindings,namespace=container.jdisc,configId=docproc/cluster.blog_post.indexing/component/com.yahoo.container.usability.BindingsOverviewHandler, Current generation: 2, Generation changed: false, Config changed: false

1522120264.318	tj-s-staging-rec10.kscn	180801/31	configproxy	configproxy.com.yahoo.config.subscription.impl.JRTConfigRequester	info	Failure of config subscription, clients will keep existing config until resolved: name=lowercasing,namespace=search.querytransform,configId=default/searchchains/chain/blog_post/component/com.yahoo.search.querytransform.VespaLowercasingSearcher, Current generation: 2, Generation changed: false, Config changed: false

This means the proxy could not subsribe any configserver to get config info right? It looks like I'm failed to set up a config server cluster. One config server 'down', configproxys on all nodes are ‘blind’.

**Comment by smorgrav** [comment]
@FrankYu0502 Looks to me like the configservers on host2 and host3 does not know about the application you deployed (but they are up and running and answer as they should).

One possible reason for this is that there is something wrong with the zookeeper setup/communication. 

When you restart the configserver - what does it say about the Zookeeper quorum?

**Comment by knowmara** [comment]
Hi,
I dumped the heap of the config server java process, but I found that the size of the InnerNodeVector in the ZooKeeperServerConfig variable of the ZooKeeperServer class instance is only 1, although I have set up three configServers. Because of dependency injection, I find it difficult to find the code segment that constructs the ZookeeperServerConfig class instance according to my setting, can you tell me the location of the source code?

**Comment by FrankYu0502** [comment]
@smorgrav 
After restarting the configserver on host1, host1, host2, host3 configproxy could communicate with configserver on host1. Nothing has been changed on Zookeeper.

I paste all relevant files here:

hosts.xml:
<?xml version="1.0" encoding="utf-8" ?>

<hosts>
  <host name="tj-s-staging-rec09.kscn">
    <alias>node1</alias>
  </host>
  <host name="tj-s-staging-rec10.kscn">
    <alias>node2</alias>
  </host>
  <host name="tj-s-staging-rec11.kscn">
    <alias>node3</alias>
  </host>
  <host name="tj-s-staging-rec12.kscn">
    <alias>node4</alias>
  </host>
</hosts>

services.xml:
<?xml version='1.0' encoding='UTF-8'?>

<services version='1.0'>
  <admin version="2.0">
    <adminserver hostalias="node1"/>
    <configservers>
      <configserver hostalias="node1" />
      <configserver hostalias="node2" />
      <configserver hostalias="node3" />
    </configservers>
  </admin>

  <container id='default' version='1.0'>
    <search/>
    <document-api/>
    <nodes>
      <node hostalias="node1"/>
      <node hostalias="node2"/>
      <node hostalias="node3"/>
      <node hostalias="node4"/>
    </nodes>
  </container>

  <content id="blog_post" version='1.0'>
    <redundancy>2</redundancy>
    <search>
      <visibility-delay>1.0</visibility-delay>
    </search>
    <documents>
      <document mode='index' type='blog_post'/>
    </documents>
    <nodes>
      <node hostalias="node1" distribution-key="0"/>
      <node hostalias="node2" distribution-key="1"/>
      <node hostalias="node3" distribution-key="2"/>
      <node hostalias="node4" distribution-key="3"/>
    </nodes>
    <engine>
      <proton>
        <searchable-copies>1</searchable-copies>
      </proton>
    </engine>
  </content>

</services>

default-env.txt
# Copyright 2017 Yahoo Holdings. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
fallback VESPA_HOME /home/work/vespa
override VESPA_USER vespa
override VESPA_CONFIGSERVERS tj-s-staging-rec09.kscn,tj-s-staging-rec10.kscn,tj-s-staging-rec11.kscn

**Comment by bratseth** [comment]
It's created by com.yahoo.vespa.model.container.configserver.ConfigserverCluster
(you can find such things by finding usages of the config builder - ZooKeeperServerConfig.Builder).
If you look at that code you'll find the config is created by reading the "addr_configserver" environment variable, and using localhost if it is not set. So, perhaps you didn't set it on the config servers?

**Comment by FrankYu0502** [comment]
@bratseth 
How to set "addr-configserver" on the config servers? (set it on VESPA_HOME/conf/vespa/default-env.txt in all hosts?)

**Comment by knowmara** [comment]
Sorry, I didn't pay attention recently. I also found that I needed to do this setup by reading the code. I set up "services.addr_configserver" and the cluster was successful.
But there is a problem, config server seems to deploy only one application. When I create two tenants, each one in turn deploy an application, I will be prompted config server has been assigned to the first deployed application, does this mean a config server cluster can only deploy one application?

**Comment by bratseth** [comment]
Thanks for reporting back. The addrs_configserver thing is actually unnecessarily confusing - well clean this up!

Regarding multiple applications: That is supported but it is only really needed if you create a multi-tenant hosted system. There's a lot to that which we don't document currently Is it really something you need to do?

**Comment by knowmara** [comment]
Thanks.
We do need deploy multiple applications, because we want to use vespa as a platform to support the recommendation of many businesses(about ten+).If one config server for one application, the operation and maintenance will be very troublesome.

**Comment by bratseth** [comment]
@FrankYu0502 to be clear, either add the line 
override services.addr_configserver configserver1FQDN,configserver2FQDN,configserver3FQDN
to your VESPA_HOME/conf/vespa/default-env.txt
or set this as an environment variable on all the config server hosts.

**Comment by bratseth** [comment]
@knowmara ok, it's possible to do that - I know some external customers are doing it (and of course we do it on a massive scale). All the steps you'll need are not documented though, and some will require digging deeper into how things work.

Are your recommendation services are managed by different dev teams with different release cycles etc.? Otherwise, you can have one app with 10 content clusters if they need to scale separately (or otherwise just 10 document types in the same cluster.)

**Comment by knowmara** [comment]
Thank you very much. 
Now it is configured like this. I have also created several tenants,  but I will be prompted config server has been assigned to the first deployed application  when deploying one more application.

**Comment by knowmara** [comment]
Yes, our recommendation services are managed by different dev teams.That's the problem.

**Comment by bratseth** [comment]
Ok. Any interest in deploying those applications to our hosted platform on AWS instead of rolling your own? We'll open that up to some select users soon.

Otherwise I'll try to give some pointers when you run into problems, but you'll probably need to figure out a number of things on your own. For the problem you mention: You need to set up the config servers independently of any of the hosted applications. The config servers is a "standalone container application", i.e a container configured from an application package directly with no config server attached. The application package you currently use for the config server cluster itself is under conf/configserver-app/. The applications must use <admin version="4.0"> in services, which does not allow setting the config server nodes.

**Comment by knowmara** [comment]
Thanks. 
While our upstream backends are deployed on a private cloud, using a public cloud is inconvenient,so we tend to roll our own.

**Comment by jazoom** [comment]
> You need to run vespa-start-configserver on all the designated config servers and vespa-start-services on all the other nodes.

@bratseth I've been reading through the docs for a few hours now trying to work out why my multi-node cluster isn't starting and I didn't come across anything about `vespa-start-configserver` or `vespa-start-services`. Is there a reason these things aren't in the docs when they are a necessary step in getting a multi-node cluster working?

For the record, the error I'm seeing is as below, and may actually be unrelated to `vespa-start-configserver` or `vespa-start-services`:
```
Invalid application package: default.default: Error loading model: Multiple services/instances of the id '0' under the service/instance StorageCluster 'storage'. (This is
commonly caused by service/node index collisions in the config.).
Existing instance: storagenode on host 'vespa-1'
Attempted to add:  storagenode0 on no host
```

I'm not sure where this is coming from because I cannot see any obvious source of collision in `services.xml`. I've pretty much copied the `content` part from your examples. If this is unrelated I'll be happy to make another issue.

```
<?xml version="1.0" encoding="utf-8" ?>
<services version="1.0">

  <admin version="2.0">
    <adminserver hostalias="vespa-1"/>
    <configservers>
      <configserver hostalias="vespa-1"/>
    </configservers>
  </admin>

  <container id="container" version="1.0">
    <document-api/>
    <search/>
    <nodes jvmargs="-Xms512m -Xmx512m">
      <node hostalias="vespa-1"/>
      <node hostalias="vespa-2"/>
      <node hostalias="vespa-3"/>
    </nodes>
  </container>

  <content id="music" version="1.0">
    <search>
      <visibility-delay>1.0</visibility-delay>
    </search>
    <redundancy>2</redundancy>
    <documents>
      <document type="music" mode="index"/>
      <document-processing cluster="container"/>
    </documents>
    <nodes>
      <node hostalias="vespa-1" distribution-key="0"/>
      <node hostalias="vespa-2" distribution-key="1"/>
      <node hostalias="vespa-3" distribution-key="2"/>
    </nodes>
  </content>

</services>
```

**Comment by jazoom** [comment]
Update: apparently the below line (which I copied from an example) was causing that last error. Then I didn't get the previous error about storage. I guess you cannot use the same node for config and for content or something.

`<document-processing cluster="container"/>`

**Comment by bratseth** [comment]
>  I didn't come across anything about vespa-start-configserver or vespa-start-services

They are described in http://docs.vespa.ai/documentation/reference/files-processes-and-ports.html
but not in the quick-starts because the docker image autostarts both. This is a tradeoff between simplifying quickstarts and providing enough understanding to progress later. I think we are too far towards the ease of getting started end currently. I created https://github.com/vespa-engine/vespa/issues/5586 to follow up on that.

I'll add more responses.

**Comment by bratseth** [comment]
Improved error message: https://github.com/vespa-engine/vespa/pull/5588

**Comment by bratseth** [comment]
The first error message I'm unable to reproduce with the services.xml you quote. Please provide the hosts.xml file as well if you are interested in getting to the bottom of that one.

**Comment by jazoom** [comment]
> Please let me know if you found an example which does not do this.
I got it from here but it seems I missed that extra tag. My mistake: https://github.com/vespa-engine/sample-apps/blob/master/basic-search-on-docker-swarm/src/main/application/services.xml

**Comment by jazoom** [comment]
> The first error message I'm unable to reproduce with the services.xml you quote. Please provide the hosts.xml file as well if you are interested in getting to the bottom of that one.

```
<?xml version="1.0" encoding="utf-8" ?>
<hosts>
  <host name="vespa-1">
    <alias>vespa-1</alias>
  </host>
  <host name="vespa-2">
    <alias>vespa-2</alias>
  </host>
  <host name="vespa-3">
    <alias>vespa-3</alias>
  </host>
</hosts>
```

env config:
```
fallback VESPA_HOME /opt/vespa
override VESPA_USER vespa
override VESPA_UNPRIVILEGED no
override VESPA_CONFIGSERVERS vespa-1
```

That error went away when I added a new node `vespa-config` and used that as the admin/config node. This makes me assume that error meant you cannot use the same node as admin/config as well as container/content.

**Comment by jazoom** [comment]
I tried it to keep things simple at first. Also, I have no idea how much RAM that service wants and I figured since the container/content nodes want over 1GB of RAM I may as well save the space by using one of them as the config/admin node. I still have no idea how much RAM the admin node requires but it's running at a lower value than the others now so it's all good.
