### ISSUE TITLE
Backups? Snapshots?

### ISSUE THREAD

**Issue by jazoom** [vespa-engine/vespa#5495]
I just had a read through the documentation and couldn't find anything about backups.

For example, Elasticsearch has built-in snapshot functionality to do incremental backups to AWS etc.

How do you efficiently do backups for large data sets with Vespa?

**Comment by bratseth** [comment]
You can do this using the visit API: http://docs.vespa.ai/documentation/content/visiting.html

It's not that common to back up the data because Vespa makes multiple copies of the data internally (by default: 2) and automatically detects and repairs losses some data copy.

**Comment by jazoom** [comment]
Elasticsearch also has multiple copies of data but that didn't stop me from stupidly deleting the production database instead of the development database. Luckily I had an off-site backup. Do some companies seriously not have database backups?

I saw `visiting` before in my reading. So essentially we need to implement our own incremental backup system using update times of documents or something?

**Comment by jazoom** [comment]
Thank you for taking the time to respond.

**Comment by bratseth** [comment]
Sorry, we don't have an internal last write time any more (we used to have another streaming-only engine that had this, but we recently removed it because the current, search-enabled one (proton) has outcompeted it on every front). I'll remove this from the doc.

Deletions + incremental backups does not compute so you'll need to add a "deleted" field instead and filter out those documents from searches (you could write a searcher which adds that to every query). If you make the "deleted" field a timestamp you can also have a gc job which removes documents after some period (synchronized with your backup strategy). If you have personal data you need to take GDPR into account. 

I would avoid all this complexity by doing full backups only. Storage which you don't need to access is very cheap, and since the only purpose of this is to protect against application/operator errors causing catastrophic data loss, which have low probability, you don't really need frequent backups or fast restore.

**Comment by jazoom** [comment]
> I would avoid all this complexity by doing full backups only.

Yeah, I've been trying to avoid complexity as much as possible. I've been spoiled by Elasticsearch's incremental backups since they work very well, even handing deletions. I do like Elasticsearch but Vespa's promise of ranking with tensors is too enticing to pass up.

Thanks again for your help.

**Comment by sunil924** [comment]
Do you suggest full daily backup for hugh systems as well? I have system having 75M documents(~100+ fields) and continuous feeding of data. Taking backup every day will not be a small task.

Also what is the suggested way to take the complete backup?

**Comment by kkraune** [comment]
Follow up in #25737
