### ISSUE TITLE
Inconsistent handling of floats in result summaries

### ISSUE THREAD

**Issue by jazoom** [vespa-engine/vespa#5624]
I've got something like this in my search definition:

```
      struct obj-struct {
          field date type long { }
          field price type float { }
      }
      field obj type array<obj-struct> {
          indexing: summary
      }
```

All objects indexed have the `price` field with 2 decimal places.

When requesting the document via an HTTP GET call it is returned as expected:

```
{
...
"obj": [
      {
        "date": 1511407947831,
        "price": 34.62
      }
    ]
...
}
```

But whenever the same document is returned as part of a search result it returns like this:

```
...
{
"obj": [
      {
        "date": 1511407947831,
        "price": 34.61999893188477
      }
    ]
...
}
```

I understand rounding of floats can sometimes do this but is there a reason why Vespa wouldn't return the same values as part of a search summary and as part of a GET request?

**Comment by bratseth** [comment]
The reason is that there is a float->long->float conversion involved in the search path when you use float fields. This is because we have changed to a more modern transfer protocol but have yet to change the object-level API to the results, which causes a level of conversion. This conversion will be removed, eventually, hopefully at Vespa 7 in Q3.

That said, you can still get imprecisions with float values of course. For money it is usually preferable to use ints and convert to decimal notation at rendering time.

**Comment by jazoom** [comment]
Okay, at least we know what's going on here.

> For money it is usually preferable to use ints and convert to decimal notation at rendering time.

True that, but in this case unfortunately that would be an enormous undertaking in rewriting lots of code in several apps. I might build rounding into the Vespa database interface code for now.
