### ISSUE TITLE
How to add a word segmentation plugin on Vespa?

### ISSUE THREAD

**Issue by theseusyang** [vespa-engine/vespa#5893]
Hi Team,
How to add a word segmentation plugin or a dictionary on Vespa?

Thanks

**Comment by bratseth** [comment]
**1:**
You can do query-side segmentation by adding a searcher: 
Doc: http://docs.vespa.ai/documentation/searcher-development.html
Sample app with a searcher: https://github.com/vespa-engine/sample-apps/tree/master/basic-search-java
Searchers can access and modify the query by query.getModel().getQueryTree().

If you want hard segments (no recall if the document does not contain the full segment as consecutive terms), replace the individual terms by a PhraseItem.
Otherwise, you can keep recall as-is and affect ranking by increasing the connectivity between terms in a segment by calling setConnectivity(double) on Items in the query tree.

There are some searchers in the package which does this kind of stuff, https://github.com/vespa-engine/vespa/tree/master/container-search/src/main/java/com/yahoo/search/query/rewrite/rewriters

**2:**
If you don't want to write code you can also do this using semantic rules: 
http://docs.vespa.ai/documentation/query-rewriting.html
You'll find something there about adding an FSA file which can encode a large number of segments.
(Under the hood this of of course just another searcher with some special-purpose config.)
