### ISSUE TITLE
Ranking feature Emission from query tree clauses for matching 

### ISSUE THREAD

**Issue by vandit-thakkar** [vespa-engine/vespa#6009]
The ranking expression is formed with rank features and constants. http://docs.vespa.ai/documentation/reference/rank-features.html describes all the features we can use, we have` matches(<field_name>,<term_position>)` as a rank feature which returns 0/1. 

Now, can't we have `matches(label)` where label represents a label of a QueryTree item [ representing something like `( title : samsung )`] perhaps https://github.com/vespa-engine/vespa/blob/master/container-search/src/main/java/com/yahoo/prelude/query/BlockItem.java. 

While query evaluation, anyways, ( title : samsung ) checking happens for all documents, so can't this emit a rank feature, referenced by its label or anything which represents `title:samsung`. 

I believe while preparing any vespa application (vespa-deploy prepare), it's checked if a match feature's field name is in index environment. https://github.com/vespa-engine/vespa/blob/master/searchlib/src/vespa/searchlib/fef/parametervalidator.cpp, that's absolutely fine. So, if Vespa had `matches(label)` type feature, it can be checked only at query time that the field of (field, term) which that label refers to is in index environment or not. 

If this doesn't compromise with Vespa design principles, please provide such feature such that hardcoding of field_name in ranking expression can be avoided.

**Comment by bratseth** [comment]
Yes, I think creating a matchedLabel(label) feature would be simple to do. How exactly does this help in your use case though?

There's nothing wrong with mentioning the field names in the ranking expression. The fields are defined ("hardcoded") in the same file anyway, and it is fine to have ranking expressions that are hundreds of lines long (you can put them in a difference file and refer if you want to).

Or, if you just want fieldMatch over all the fields without mentioning them you can use the "match" feature.

**Comment by vandit-thakkar** [comment]
Yes, as you said it's simple to do, but after that, I have realized that it's not cost of larger rank expression with a lot of rank features as you suggested, with the correct set of experiments I can almost confirm that numbers of throughput are in sync with this understanding, so I am trying to understand when and how rank features are calculated, you can close this issue with a short guide or reference of how one can know all in and out of rank feature calculation in Vespa.

**Comment by bratseth** [comment]
The entire thing is complicated and we don't have up to date design documentation, but what's relevant here:
There is a rank computation setup phase happening once a query is received on a content node. At that point all the features which are constant for that query are calculated once and then reused for all documents while rank is computed. 

A few other things you may be interested in:
- All features are computed once per document (or query) regardless of how many times they are accessed.
- Computing rank features is lazy: If they are not needed to compute the final score (e.g due to being in the wrong branch of an "if", they are not computed at all. 
- For all practical purposes (such as the above), macros are rank features.

**Comment by vandit-thakkar** [comment]
> _There is a rank computation setup phase happening once a query is received on a content node. At that point all the features which are constant for that query are calculated once and then reused for all documents while rank is computed._
That's sounds very logical. But in one of the experiments, with 800 `matches(<field_name>,<term_pos>)  ` type rank features in ranking expression, 20 of which are evaluated differently for different documents (triggered by `rank()` in YQL ), so I can understand that rest of 780 are calculated only once. For given setup, I get 118 qps throughput. Now keeping everything else same, I add 800 more features of `matches(<field_name>,<term_pos>)  ` type in rank expression, still the query has `rank()` which calculates only 20 of them different for different documents. So I expect rest of 1580 to be calculated only once as they are same (0) for all documents, but throughput with this comes only 56 qps. Can you guide what might be happening wrong?

**Comment by bratseth** [comment]
You can see the code which causes matches(field, term) to be constant if the field is not mentioned here: https://github.com/vespa-engine/vespa/blob/master/searchlib/src/vespa/searchlib/features/matchesfeature.cpp

(You end up with zero handlers in the executor because util::getTermFieldHandle(env, i, fieldId) returns NULL).

Even though the features are constant you still need to run thought and compute the ranking expression over 780 (or is it 1580?) additional matches(field, term) nodes when evaluating your ranking expression.

How many documents are matched on average here - still 40k? If you tell we that number and whether it is 780 or 1580 I'll run a test to sanity check this.

Is 40k (or whatever) your target average matches per node or across all nodes?

Did you consider just using "match" as the ranking expression?

**Comment by vandit-thakkar** [comment]
> Even though the features are constant you still need to run through and compute the ranking expression over 780 (or is it 1580?) additional matches(field, term) nodes when evaluating your ranking expression.

So, do you mean that these 780 match features (which are not triggered by rank() from the query, that means there is no use of those 780 features for the particular query ) are calculated (even though evaluated as 0)  **for all matched documents**. 

from TermFieldHandle, I understand that it's a handle of a (term, field), which has "already stored" info of matching of (term, field). So you wanted to say that this value is calculated only once for these 780 fields, then assigned to all documents (in TermFieldMatchData object) and then while calculating final expression value for every document, it **gets all these values through handle**, (which has to happen) and because of that, having more **useless features for a query** have clear overhead. Please correct me if I am wrong. 

In the experiment I did, I had 60k matching set, from 10M documents across 2 nodes. And I wrote 20 items of kind `<field> contains <term>` in rank() in YQL. And I had 800 match features in ranking expression, 780 of them are not of use for me **for this query**. In my comment, I tried to tell you that, for the same query with 780 extra match features QPS is 118 qps and with 1580 extra match features QPS is 56 qps, which shows it's costlier with increasing match features.

**Comment by bratseth** [comment]
You are more or less correct, but a simpler way to put it: Your ranking expression is something like "a + b + c + ..." and this is compiled once, not once per query (that would be way too slow).

So, even if b and c (and so on) is 0 for a given query and that is only computed once, we still evaluate the full (compiled) expression "a + b + c + ...", and if everything else is cheap this dominates cost.

Thanks for the numbers. I'll sanity check the performance, but they seem reasonable.

Two remaining questions for you:
- Do you need to match 40k documents per query on average _over the entire corpus_, or _per node_?
- Did you consider just using "match" as the entire ranking expression?

**Comment by vandit-thakkar** [comment]
40k documents per query over entire corpus of 10 M docs 
ranking expression looks like 

matches(field_1,1)*query(field_1__1)+
matches(field_1,2)*query(field_1__2)+
….
matches(field_1,20)*query(field_1__20)+

matches(field_2,1)*query(field_2__1)+
matches(field_2,2)*query(field_2__2)+
matches(field_2,3)*query(field_2__3)+
....
matches(field_2,20)*query(field_2__20)+

……
……
<same for some 40 fields>

so this way, I have 800 (20*40) match features.

**Comment by bratseth** [comment]
Ok, the numbers you measure seems reasonable. 

At 118 qps ad 30.000 hits per query per node you are evaluating the ranking expression with 800 children 4.720.000 times per second. That's pretty awesome ... and dominates your cost (since everything else you are doing is cheap) which is why doubling it halves throughput.

Still wondering about:
- Do you need to match 40k documents per query on average over the entire corpus, or per node?
- Did you consider just using "match" as the entire ranking expression?
