### ISSUE TITLE
How to store intermediate results during getting candidate?

### ISSUE THREAD

**Issue by FrankYu0502** [vespa-engine/vespa#6100]
Hey guys,

The following is the part of my code to build query tree:
    baseItem = new OrItem();
    baseItem.addItem(new WordItem("X", "tag_list")); //field tag_list type array <<String>>
    baseItem.addItem(new WordItem("Y", "tag_list"));
    baseItem.addItem(new WordItem("Z", "tag_list"));
    ...
    QueryTreeUtil.andQueryItemWithRoot(query, baseItem);

After ranking, how could I know the result(each item) is obtained from that tag("X", "Y" or "Z")?

**Comment by jobergum** [comment]
You want to know which of the query terms matched the the tag_list field?

**Comment by FrankYu0502** [comment]
Thanks for your reply! Sorry for confusing.

Giving the reasons why we recommend particular items(like books, musics) are necessary. Those reasons are depends on some intermediate results during scoring(rank profile) or on recall logic.

For example, our music has tag value "popular" and "classical" in tag_list. After execution.search(query) in search chain, I get one Hit "hey jude" (setHits(1)). How could I know the recall logic. How could I know "hey jude" coming from "popular" or "classical" or both during recalling. Denpends on this information, I could give the reason why I recommend "hey jude".

baseItem.addItem(new WordItem("popular", "tag_list"));
baseItem.addItem(new WordItem("popular", "tag_list"));

**Comment by lesters** [comment]
So, if you set up the query as you do above, the hits that are returned will have either "popular" or "classical" (or both) in their "tag_list" attribute. You can simply inspect the value of that field for each hit to see which tag it matched. 

In your searcher you would do something like this:

```
// set up query
OrItem baseItem = new OrItem();
baseItem.addItem(new WordItem("popular", "tag_list"));
baseItem.addItem(new WordItem("classical", "tag_list"));
query.getModel().getQueryTree().setRoot(baseItem);

// perform search
Result result = execution.search(query);
execution.fill(result);  // this is important to be able to inspect data

// inspect the results
for (Hit hit : result.hits().asList()) {
    if (hit.isMeta()) continue;
    Object tagsListField = hit.getField("tag_list");
    if (tagsListField instanceof Inspectable) {
        Inspector tags = ((Inspectable) tagsListField).inspect();
        for (int i = 0; i < tags.entryCount(); ++i) {
            String tag = tags.entry(i).asString();
            // Do something with the tag here - it is either "popular" or "classical"
        }
    }
}
```

More information about inspecting here: http://docs.vespa.ai/documentation/reference/inspecting-structured-data.html#use-case-accessing-array-attributes

**Comment by jobergum** [comment]
If you have few query terms searching the tag_list you could use the matches(tag_list,N) ranking feature and pass it up as a ranking summary feature but just parsing the summary of the field is the simplest. If your recall query list is large, you should consider using one of the multi-value query operators described here http://docs.vespa.ai/documentation/reference/advanced-search-operators.html

**Comment by FrankYu0502** [comment]
Thanks so much for your help. It helps us a lot.

There are hundreds of tag values in our tag_list, and some tags are going to be combined with user profile information during recalling. The recall logic is very complecated and is not as simple as either "popular" or "classical". Inspecting the results looks like I should re-write all the recall logics after getting the hits. Is this the only way to get over the issue?

**Comment by jobergum** [comment]
If you have categorisation (e.g popular, new releases, whatnot) Vespa grouping might also be something you could look at to instead of one single flat hit list you can ask vespa do get top recommendations per category/tag using grouping and order the groups by relevance/count. See http://docs.vespa.ai/documentation/grouping.html

**Comment by FrankYu0502** [comment]
Thanks!

**Comment by FrankYu0502** [comment]
http://docs.vespa.ai/documentation/reference/inspecting-structured-data.html doesn't mention any thing about tensor.

If tag_list is defined like this: "field tag_list type tensor(x{})" or "type tensor(x[100])", in searcher should I access the tag_list just like field that is of array type?

**Comment by lesters** [comment]
Yes, a field that is a tensor it is directly accessible:

```
Result r = execution.search(query);
execution.fill(r);
for (Hit hit : r.hits().asList()) {
    Object field = hit.getField("tag_list");
    if (field instanceof Tensor) {
         Tensor t = (Tensor)field;
         // do something with tensor
    }
}
```

However, whether or not this is useful in your case, depends on a couple of things.

The first is how you would represent this using tensors. In tensors, we have dimensions which are either indexed or mapped, representing dense and sparse tensors respectively. In your case you would probably have a sparse tensor with tag names as elements along a dimension. Now, the values are doubles, and could in your case be either 1.0 or some floating point indicating how representative that tag is for that document. To find the tags you would do a tensor join between the document and the query. In general though, it's the values you do math on, so it's not straightforward to extract the actual tag. You would have to iterate through the cell values using the Java specific tensor interface and extract the tags. 

The second is regarding performance. In our Java implementation, doing joins over mapped tensors are not very performant, but indexed tensors are.

This leads to another option, which would be to represent tags numerically instead of with text. You would do a join to fund the numeric values of the tags, but this is much faster with an indexed tensor. However, you would still need to iterate through cell values and you would introduce a cost to look up the textual values of the tags. The added complexity is not necessarily worth it. 

Unfortunately, Vespa currently does not support returning tensors in document summary features, otherwise you could simply do this on the ranking side.

How many hits are you returning on average? Iterating through the inspectable list as mentioned in a previous response might not be a costly alternative.

Cheers,
- Lester
