### ISSUE TITLE
After change the VESPA_HOME from /opt/vespa to /happy-data/app/vespa, the ./vespa-start-configserver can not work well.

### ISSUE THREAD

**Issue by ggservice007** [vespa-engine/vespa#6292]
After change the VESPA_HOME from /opt/vespa to /happy-data/app/vespa, the ./vespa-start-configserver can not work well.

The problem is that the port 19071 can not start to listen.

**Comment by arnej27959** [comment]
1: try
 /happy-data/app/vespa/bin/vespa-start-configserver

2: if it doesn’t work please paste entire output and anything relevant from /happy-data/app/vespa/logs/vespa/vespa.log

**Comment by ggservice007** [comment]
only one process
```cmd
vespa    20579     1  0 09:20 ?        00:00:00 vespa-runserver -s configserver -r 30 -p /happy-data/app/vespa/var/run/configserver.pid -- java -Xms128m -Xmx2048m -XX:+PreserveFramePointer -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/happy-data/app/vespa/var/crash -XX:OnOutOfMemoryError=kill -9 %p -Djava.library.path=/happy-data/app/vespa/lib64 -Djava.awt.headless=true -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.net.client.defaultConnectTimeout=5000 -Dsun.net.client.defaultReadTimeout=60000 -Djavax.net.ssl.keyStoreType=JKS -Djdisc.config.file=/happy-data/app/vespa/var/jdisc_core/configserver.properties -Djdisc.export.packages= -Djdisc.cache.path=/happy-data/app/vespa/var/vespa/bundlecache/configserver -Djdisc.debug.resources=false -Djdisc.bundle.path=/happy-data/app/vespa/lib/jars -Djdisc.logger.enabled=true -Djdisc.logger.level=ALL -Djdisc.logger.tag=jdisc/configserver -Dfile.encoding=UTF-8 -Dzookeeperlogfile=/happy-data/app/vespa/logs/vespa/zookeeper.configserver.log -cp /happy-data/app/vespa/lib/jars/jdisc_core-jar-with-dependencies.jar com.yahoo.jdisc.core.StandaloneMain standalone-container-jar-with-dependencies.jar
```

**Comment by arnej27959** [comment]
from your attached vespa.log this is because the configserver tries to load the same bundle twice:

[2018-06-28 01:17:18.558] DEBUG   : jdisc/configserver /com.yahoo.jdisc.core.FelixFramework     OSGi bundle 'container-disc' requires install from 'zkfacade-jar-with-dependencies.jar'.
[2018-06-28 01:17:18.558] DEBUG   : jdisc/configserver /com.yahoo.jdisc.core.FelixFramework     Installing OSGi bundle from 'file:/happy-data/app/vespa/lib/jars/zkfacade-jar-with-dependencies.jar'.

[2018-06-28 01:17:28.584] INFO    : configserver     Container.com.yahoo.container.core.config.BundleLoader     Installing bundle with reference 'LocalFileDb:components/zkfacade.jar'
[2018-06-28 01:17:29.800] WARNING : configserver     Container.com.yahoo.container.di.Container 
        Failed to set up first component graph. Exiting within 60 seconds.
        exception=
        java.lang.RuntimeException: Could not install bundle 'file 'LocalFileDb:components/zkfacade.jar''
...
        Caused by: java.lang.RuntimeException: com.yahoo.jdisc.application.BundleInstallationException: Bundle symbolic name and version are not unique: zkfacade:6.0.0

**Comment by arnej27959** [comment]
when I start configserver from /opt/vespa it seems to "just work".  I have these files:
$ ls -l /opt/vespa/lib/jars/zkfacade-jar-with-dependencies.jar /opt/vespa/conf/configserver-app/components/zkfacade.jar 
lrwxrwxrwx. 1 arnej arnej      54 Jun 26 12:05 /opt/vespa/conf/configserver-app/components/zkfacade.jar -> /opt/vespa/lib/jars/zkfacade-jar-with-dependencies.jar
-rw-r--r--. 1 arnej arnej 3102443 Jun 26 11:55 /opt/vespa/lib/jars/zkfacade-jar-with-dependencies.jar

my guess is that you have a symlink in
/happy-data/app/vespa/conf/configserver-app/components/zkfacade.jar 
that still points to /opt/vespa, and this causes problems because the container is now asked to load two bundles with same id (name+version) which are not the same file.

GV: does my guess sound plausible to you?

**Comment by gjoranv** [comment]
@arnej27959, yes, it's probably related to the contents of the configserver-app folder.

@ggservice007, please take a look at the contents of  `/happy-data/app/vespa/conf/configserver-app/components/`. Each jar file should only occur once as a symlink to the corresponding file in  `$VESPA_HOME/lib/jars`.

**Comment by ggservice007** [comment]
Thank you, I will try it later.
