### ISSUE TITLE
Potential lack of synchronization accessing snapshots in MetricManager

### ISSUE THREAD

**Issue by tedyu** [vespa-engine/vespa#7169]
Inside initializeSnapshots :
```
            snapshots.add(new MetricSnapshotSet(snapshotPeriods.get(i).getSecond(),
                                                snapshotPeriods.get(i).getFirst(),
```
It seems the method should be synchronized so that accesses to snapshots are coordinated.

**Comment by bratseth** [comment]
I don't think so because initialize is part of construction (initializeSnapshots is called from the constructor only), and construction is single threaded, and the metrics object created is only accessed from VespaFeedHandlerStatus after it passes other memory barriers. 

That handler, and this metrics code is deprecated and will be removed on Vespa 7 later this year.
