### ISSUE TITLE
Understanding when to use Predicate Fields

### ISSUE THREAD

**Issue by theconnectionist** [vespa-engine/vespa#8182]
I played with the basic features of Vespa and love it. Exploring use of Predicate Fields and wondering if it works for my use case as I think it does.

Consider a corpus of news articles which can be tagged with one or more of these tags: {"economy", "sports", "politics", "crime", "technology"}. A simple way to handle this is to define a field "Tags" of type string and throw in one or more of these tags to classify the new article. To execute the query "Tags contains sports or politics or economy", Vespa presumably gets the postings for each of these terms and ORs them. Clearly, this could get expensive when the cardinality of categories increases and/or there are many such fields that characterize a document.

With Predicate Fields, each news article can be assigned a predicate that precisely characterizes it. For example, a news article tagged with sports and crime gets "Tags in [sports, crime]". If all news articles are similarly assigned appropriate predicates, Vespa presumably executes the query "... where predicate(predicate_field_name,  {"0x1" : {"Tags" : ["sports", "politics", "economy"]}} a bit more efficiently using the index specifically built for this predicate.

Is this a correct read of the advantage of using the predicate field feature -- **that I could get faster query execution time** (at the cost of some modeling complexity and memory for the index) because the index has pre-populated matches for some, presumably frequently used, criteria?

What I was looking for when I stumbled on this feature is the ability to avoid multiple OR operations when looking for some commonly occurring where clauses. I understand Vespa doesn't support bitwise operators (e.g. assign a bit position for each category tag in my example and query with a bitmask that expresses the desired combination of categories) so I was scouring the docs for something that might work with comparable efficiency. Conceptually, this feature appears to be a good approximation of what I was seeking.

**Follow up question**:

Does an update of a predicate field work like it does for other field types? For example, if one of my news article's category tags changes, I would update the predicate field for that article to cause Vespa to update the corresponding index.

Thanks you for your consideration.

**Comment by baldersheim** [comment]
There are multiple questions/concerns here.
Q - Is a large OR expensive ?
A - It can be. The main scaling dimension for any query in Vespa is the number of hits the query will produce. If a query covers 1M documents it actually cheaper if this is produced by an OR instead of an AND as for an AND all terms must match, while for an OR only 1 term need to match. But normally if you have N terms and you use AND you will get very few hits as the INETeRSECTION will be small, and if you have an OR you will get the the UNION which will be larger.

But then of course theory and practice are not always that simple. The other major scaling dimension is how much work needs to be done for each matched document. Most of this is ranking cost. Depending of your first phase ranking expression Vespa tries to find the cheapest way of evaluating the query. If the terms are needed for ranking it will be more expensive if they were under an OR rather than under an AND. However if the terms are only used as binary filters and not required for ranking they will be significantly cheaper. As the terms can have multiple posting lists depending on their use and the type with minimum set of features are chosen query time, the evaluation time can very different. The simplest variant is a simple vector of bits indicating if the term is present in this field in a document. Query time bit vectors are grouped together and iterated as a set with a bit mask making it as efficient as you would with special support for bitwise operations.

I hope this answers some of your concerns.

I will get to the other parts of your questions later on.

**Comment by theconnectionist** [comment]
Thanks for the detailed view @baldersheim . Look forward to your followup on the predicate field part of the question.

**Comment by baldersheim** [comment]
Q - Can predicate fields be updated like any other field ?
A - Yes. And it will be visible in the index and available for search once the update operation is acked. Normally within a few milliseconds.

**Comment by baldersheim** [comment]
Q - Is the tags use case suited for predicate search ?
A - No. As far as I can tell from the description of your use case the best solution is array<string>, weighted_set<string>, or the new undocumented feature(as of 6.330) with field of type 'bool' which will be a more space efficient implementation keeping only a single bit per document compared to multiple posting lists used in the array<string> case. The weighted_set solution will allow you to assign a weight(probability) to the tags you assign a article. If the article is 60%sports and 10%politics and 30%crime and you want to model that with a tags field it could be used for ranking, instead of a pure binary matching criteria.

Q - Why is predicate fields not well suited for this use case ?
A - Predicate fields are best suited when you express the 'query' in the document and the 'document' in the query. It is like reversing the problem. It is more like the document(article) deciding which query features it requires to be a match.
The 'predicate' should also be very irregular and hard/impossible to solve the normal way. If you want to say in your news article things like: I am a good fit for gender:woman AND age[18...35] AND interested in [sports,crime] AND income:high AND lives_in:LONDON.
When these predicates are very different in shape and criteria predicate fields are a perfect match.
Most of the use cases I have seen with predicate fields have been user targeting where you have articles or ads that you want to show to a certain audience, and alerting where you have documents that specify as a predicate as set of conditions that is required for it to 'trigger'. If all documents have simple predicates that all the same form, just different limits you can probably express it as an ordinary query.

So in your case I would just use a tags field and leave it to vespa to choose an optimal query execution.

**Comment by jobergum** [comment]
Predicate field background (Indexing Boolean Expressions)  https://theory.stanford.edu/~sergei/papers/vldb09-indexing.pdf

**Comment by theconnectionist** [comment]
Thank you folks for your detailed explanation and additional context. Looks like the yet-to-be-documented bool field is really what I'm looking for. I'll check it out.

I'll play with book, and if allowed, array<bool> to get an efficient im-memory representation as well as faster query performance. I understand I'll have to experiment to find the right combination.
