### ISSUE TITLE
Make rendering of arrays independent of whether they are marked as attribute

### ISSUE THREAD

**Issue by bratseth** [vespa-engine/vespa#8289]
If an array field is not set in a document (i.e is null), it is usually not rendered, but if it is marked attribute it is rendered as an empty array ([]).

Make attribute rendering consistent by knowing the difference between null and empty also for attributes.

**Comment by frodelu** [comment]
@lesters Please update ticket with current status.

**Comment by lesters** [comment]
There has been some confusion of what this issue here is about. To be clear this issue tracks necessary changes to the backend to be able to differentiate between null and empty values for attribute fields. This is a larger, non-trivial change to the backend and will take considerable effort.

The first part is fixed in the mean-time as rendering of multi-value fields is now consistent across attribute- and non-attribute fields.

**Comment by geirst** [comment]
This was fixed in 2022. System test: https://github.com/vespa-engine/system-test/tree/master/tests/search/empty_fields_in_response
