### ISSUE TITLE
Grouping as tree query error message

### ISSUE THREAD

**Issue by dazld** [vespa-engine/vespa#8689]
Hey, we're trying out vespa and trying to get our collective heads around the query syntax - we're using the tree queries over YQL (easier to programmatically create them), but have hit a brick wall where the following query: 
```
{"yql":"select * from product where feature_slugs contains \"face\" limit 1  | all(group(predefined(stock_level, bucket(-inf,0), bucket(1, inf))) each(each(output(summary()))));"}
```
produces expected results, but when sent as a JSON tree:
```
{
  "select": {
    "where": {
      "contains": [
        "feature_slugs",
        "face"
      ]
    },
    "grouping": [
      {
        "all": {
          "group": {
            "predefined": "stock_level"
          },
          "each": {
            "output": "summary()"
          }
        }
      }
    ]
  },
  "offset": 0,
  "hits": 2,
  "ranking": {
    "sorting": "-score"
  }
}
```

we get an error as follows:

```
[:error
 {:id "toplevel",
  :relevance 1.0,
  :fields {:totalCount 0},
  :errors [{:code 4,
            :summary "Invalid query parameter",
            :message "Invalid request parameter: Could not set 'select.grouping' to '': Illegal query: invalid initial character for value, at: "}]}]
```

We're using clojure to talk to vespa, creating the queries as EDN then generating json from them, but that part seems to be working fine - simpler queries are producing data great. 

Vespa 7.9.16

**Comment by bratseth** [comment]
This was an actual bug, fixed in https://github.com/vespa-engine/vespa/pull/8697 - sorry about that.

This way of submitting queries is quite new and not that much used yet. Most people who build queries programmatically just add a Java component (Searcher) to their Vespa application to do it so they can use the Vespa APIs to build queries and skip one level of parsing+serialization. If you use Clojure I suppose you don't want to do that though ...

This will probably be released on Monday.

**Comment by dazld** [comment]
Thanks for quick turnaround! We'll try out the version you release and come back to you if any further issues. I'll close this for now, and reopen if there's a problem.
