### ISSUE TITLE
can i get some docs about index architecture for understand ?

### ISSUE THREAD

**Issue by zttaotao2013** [vespa-engine/vespa#8994]
rencently i start to study vespa，but i come to trouble in understanding the architecture  about Index ，and there is no explain in vespa document ，could anybody send some doc about this to my email，thanks 。 

my email : zttaotao2006@126.com

**Comment by kkraune** [comment]
Hi! Please refer to https://docs.vespa.ai/documentation/proton.html#index - the whole document should be relevant - and let us know what you think is missing (i.e. what questions you have that at not addressed). Thanks!

P.S. It is also a good start to read https://docs.vespa.ai/documentation/overview.html to get the full picture

**Comment by zttaotao2013** [comment]
thanks for your reply.
i read the url that you give me ,these docs  focus  on how use index,bud not explain how the index system is built in code ,i need help like this.
now i am reading the code of vespa about the index core conception,such as postlist,bitvector,dictionary,zcbuf,btree and so on. and i also run vespa in docker ,found that there is a lot  type of files in  index filed dir。i don't understand  how the data, struct and file is organized in the index system.

i also have a question about 0.already and 2.notalready,why this two subdb requierd to set?  how vespa is benefited from this mechanism?for one data,is it inserted to these two subdb at the sametime?

**Comment by bratseth** [comment]
You can read about read, not ready etc. here: https://docs.vespa.ai/documentation/proton.html

We have some more design documentation but we're not keeping it up to date and therefore not publishing it. You don't need to know internal details to use Vespa effectively though ... what are you trying to achieve?

**Comment by zttaotao2013** [comment]
now i am intresting about index filed, and i reseaching lucence at the same while .lucence can‘t satisfy my requirement on some business scenes，but vespa perhaps can，so i intend to know more about the difference of index mechanism between the vespa and lucence，if some more design documentation can be offered，it's very helpful for me，could  the  design documentation be shared to me even the doc is not up to date ? thanks。

**Comment by kkraune** [comment]
I am sorry we will not share the design documentation as-is, as it is at best inaccurate and misleading. As I don't know what you are looking for, I cannot easily forward a subset. Can you describe the problem you are trying to solve, then we can maybe help you? Thanks!

**Comment by zttaotao2013** [comment]
thanks for your reply.
I want to select a index system of high throughput rate for write and write，I try lucence and es ，but they can't satisfied ，and I found vespa in github, the document  describe that performance of vespa is very good，so i want to know the advance of it's index mechanism and the difference of performance between es and vespa, or are there some sucessful cases for reference in other companies except yahoo ? rencently I also read the document of the openseach of alibaba, i feel some similar with openseach in architecture，is there some relevance between opensearch and  vespa?

**Comment by bratseth** [comment]
Thanks for the explanation. The usual way that search engines achieve real-time writes is by building a small reverse index (posting list) for recent wries and merging them in the background. Since inserts quickly becomes expensive even in a quite small posting list, while merging with the large posting list takes a very long time, it is often necessary to use multiple progressively larger posting lists and merge multiple times. With a high sustained write rate this becomes quite expensive and creates a lot of garbage which must be cleaned up which leads to problems sustaining stable write and query rates. 

We used to do this in Vespa as well until about 8 years ago or so. Then we switched to a design where recent changes go into in-memory B-trees instead of a small posting lists which is then merged with posting lists in the background. (In addition they are appended to a transaction log for replay to guarantee durable writes). 

Queries always evaluate over both B-trees and posting lists on disk. Changes to B-trees are lock free by creating new nodes up to the root on inserts/removals. Queries observe immutable B-trees during their lifetime.

Since updates in larger B-trees are cheap this design avoid the need for progressively larger indexes, and generates much less garbage and large memory operations, which makes it possible to sustain a high rate of change over long periods of time. Compared to Lucene-based systems it also helps that the Vespa backend is written in C++ which avoids GC problems typically encountered with large heaps in JVMs.

You should expect an update rate of a couple of thousand to a couple of tens of thousands write operations per second per node (depending on the size of the documents etc.) while also handling a substantial query load. Partial updates of single in-memory fields (attributes) should reach above 70k writes/sec per node.

I don't know much about Alibaba opensearch and there's no relation afaik. From a quick look it seems to be a hosted service for structured search only optimized for mobile devices (i.e small data sets moved to clients etc.)

**Comment by zttaotao2013** [comment]
Hello, I have another question to confirm，the memory index of vespa use B-Tree struct, is the disk index also use B-Tree struct? or other data struct?

**Comment by bratseth** [comment]
Disk indexes (i.e the portion of the data of a field with "index" which isn't recently written and therefore is flushed to disk storage) uses a different data structure, namely a dictionary + posting list.

**Comment by zttaotao2013** [comment]
from the code，the dictionary and posting list structs make special designs，what benefits can be taken to vespa from this designs?

**Comment by bratseth** [comment]
Dense storage + fast lookup (at the cost of very expensive updates, which is what the B-trees ameliorates). It's a standard data structure in search engines.
