### ISSUE TITLE
Weirdness regarding uri type

### ISSUE THREAD

**Issue by taynaud** [vespa-engine/vespa#9444]
Hello,

I try to use an url field with an uri type. I need to use it as an uri but also to make fast exact match on the whole url.

Documentation states that (https://docs.vespa.ai/documentation/reference/search-definitions-reference.html):

```
Attribute | Added as-is as a string
```

But when I try to submit my search definition I get:

```
{
    "error-code": "INVALID_APPLICATION_PACKAGE",
    "message": "Invalid application package: default.default: Error loading model: Error in field 'url' in search definition 'site': uri type fields cannot be attributes"
}
```

with this definition of url field:
```
        field url type uri {
            indexing: summary | attribute | index
            attribute: fast-search
            rank: filter
            match {
                exact
                exact-terminator: "@@"
            }
        }
```

Is this a bug or an issue in the documentation ?

Best,

**Comment by bratseth** [comment]
It's this way on purpose, so the documentation is wrong.
Problem is that when building the query there's no way to say if you want to match the index or attribute, so the engine needs to choose, and then it chooses the index. 

Since attributes are exact match by default there's nothing to gain from typing those as url instead of string (although we could have handled that fine ... I see I write the code that rejects this but I can't remember why we were this blunt to be honest).

In any case, I think you need to define two different fields for this. If you want to keep it as a single field in the document you can define an additional field (or two) outside the document clause (i.e directly in the search clause), and let them use the document field as input, e.g

```
search foo {

    field exacturl type string {
        indexing: input my_document_url_field | attribute
    }

    ....

}
```

**Comment by bratseth** [comment]
Documentation fix: https://github.com/vespa-engine/documentation/pull/583

**Comment by taynaud** [comment]
Thank you for the explanation and the documentation fix !
