### ISSUE TITLE
spikes on search latency and cpu usage

### ISSUE THREAD

**Issue by dsisds** [vespa-engine/vespa#9446]
Hello, 
I used vespa in our search system, and it works well at the beginning.But with growing of searching and indexing qps, service becomes unstable and search errors increase dramatically due to spikes on vespa search latency.

Following is metrics of vespa search latency and cpu usage on last two days.
![image](https://user-images.githubusercontent.com/5534548/57977592-6e5a3280-7a2e-11e9-9778-e17a4eb63643.png)
![image](https://user-images.githubusercontent.com/5534548/57977602-934ea580-7a2e-11e9-84b7-5ab2680dfe91.png)

Index size is about 13G and it contains 630M documents.
Each node has 48 cpu cores and 200G memory.  And all data is saved on a 800G ssd.
Search qps is 250 and indexing qps is 4k. Most indexing operators are updating.

Looking forward to your help.
Thank you very much

**Comment by jobergum** [comment]
It's not perfectly clear to me that these cpu spikes are correlating with what I assume is the end to end latency (95percentile?) as observed from a client. Do you also have the query rate graphs for the same time period. Also to get per compoment latency breakdown would help (e.g with per rank-profile as dimensions?).  See https://docs.vespa.ai/documentation/reference/metrics-health-format.html for how to gathering metrics from Vespa. 

Still assuming that they do correlate then I think the cpu spikes and latency is likely caused by query pattern changes as not all queries have the same cpu cost/latency model.
 E.g a query with a high number of hits using and expensive ranking profile, e.g a trained model with many features in first-phase) might cause high latency/timeout errors for those specific queries. 

Vespa content node has a few maintenance jobs which runs in the background (described here https://docs.vespa.ai/documentation/proton.html) but these have low cpu impact and little or no latency impact on query serving (Their peak usage is controlled https://docs.vespa.ai/documentation/content/setup-proton-tuning.html#feeding-concurrency).With high update rate there is going to be some summary store compacting jobs which will increase cpu usage but these jobs does not impact the serving latency. 

Feel free to reach out to me per email with further details if you don't want to share them here. Thanks



 It would be nice to get a day worth of vespa.log* from one of your nodes (assuming that container and content nodes are running on the same host, if not logs from both container and random content node would help on diagnosing it).
