### ISSUE TITLE
handling missing value in XGBoost

### ISSUE THREAD

**Issue by raskr** [vespa-engine/vespa#9646]
Vespa can load XGBoost's model dump like this:
```json
[
  { "nodeid": 0, "depth": 0, "split": "f29", "split_condition": -0.1234567, "yes": 1, "no": 2, "missing": 1, "children": [
    { "nodeid": 1, "depth": 1, "split": "f56", "split_condition": -0.242398, "yes": 3, "no": 4, "missing": 3, "children": [
      { "nodeid": 3, "leaf": 1.71218 },
      { "nodeid": 4, "leaf": -1.70044 }
    ]},
    { "nodeid": 2, "depth": 1, "split": "f109", "split_condition": 0.8723473, "yes": 5, "no": 6, "missing": 5, "children": [
      { "nodeid": 5, "leaf": -1.94071 },
      { "nodeid": 6, "leaf": 1.85965 }
    ]}
  ]},
  { "nodeid": 0, "depth": 0, "split": "f60", "split_condition": -0.482947, "yes": 1, "no": 2, "missing": 1, "children": [
    { "nodeid": 1, "depth": 1, "split": "f29", "split_condition": -4.2387498, "yes": 3, "no": 4, "missing": 3, "children": [
      { "nodeid": 3, "leaf": 0.784718 },
      { "nodeid": 4, "leaf": -0.96853 }
    ]},
    { "nodeid": 2, "leaf": -6.23624 }
  ]}
]
```
But what value Vespa should treat as `missing` is not deterministic. How can I tell Vespa the missing value? (XGBoost's default is NaN)

**Comment by lesters** [comment]
You are right, Vespa does not currently handle the "missing" attribute in XGBoost models, which is something that can lead to erroneous evaluation values. Currently, if a split feature is missing (e.g. a document field that hasn't been fed), the feature evaluates to NaN (if type is double) and the if-statement will automatically be false. Thus Vespa follows the "no" path, which in the example you give here will be wrong. 

Vespa has a highly optimized code path for evaluating decision trees like this, and to test for missing values at every branch would increase evaluation time significantly. We do have an idea for a fix, though. Currently during import, the branches are converted to if's: `if (feature < split ; yes-branch ; no-branch)`. This works if missing points to the no-branch. The fix is to "invert" the comparison when missing points to the yes-branch: `if ( !(feature >= split) ; yes-branch ; no-branch)`. This should be a simple fix and give correct results, however the downside is that the optimized code path won't be triggered. We would have to fix that as well.

I'll try to get to this ASAP.

Until then the best approach is to ensure that you don't have documents with missing values! Of course this is not always feasible, so a "fix" would be to handle missing values on your own: in your training set, fill out missing values with some value (for instance 0.0), and specifically add your own functions in the rank profile to handle missing values for those features that can result in NaNs. For instance, for your example, if the feature f29 is from some calculated feature from Vespa, e.g. nativeRank, the value is never NaN. But if f56 is from a document attribute, it can be missing if not fed. In this case you can insert default values:

```
function f56() {
    expression: if (isNan(attribute(foo), 0.0, attribute(foo) )
}
```

Whether or not this is a feasible approach depends on the number of features I guess.

**Comment by raskr** [comment]
Thank you for rapid reply!
Surely XGBoost's default `missng` is NaN, but there are cases of other values (e.g. those who using sparse features set `missing = 0` usually).
Is it difficult to accept external settings like this?

**Comment by lesters** [comment]
Should now be fixed with https://github.com/vespa-engine/vespa/pull/10665
